/**
 * 150-Guide Dominance Plan (Cat-First Strategy)
 * 
 * Clusters: Cat Litter (50), Cat Furniture (40), Dog Beds (30), Micro-Intent (30)
 * Schedule: 12 weeks, Cat Litter priority in weeks 1-4.
 * Includes cannibalization check and difficulty estimates.
 */

// ============= TYPES =============

export interface ScalingGuide {
  slug: string;
  title: string;
  primaryKW: string;
  secondaryKWs: string[];
  intent: 'commercial' | 'informational' | 'comparison';
  priority: number;
  cluster: 'cat-litter' | 'cat-furniture' | 'dog-beds' | 'micro-intent' | 'dog-training' | 'cat-enrichment' | 'dog-travel' | 'dog-grooming';
  week: number;
  role: 'cornerstone' | 'hub' | 'subguide';
  internalLinksTarget: number;
  linksTo: string[];
  difficulty: 'low' | 'medium' | 'high';
}

export interface WeeklySchedule {
  week: number;
  label: string;
  guides: ScalingGuide[];
  focus: string;
}

export interface CannibalizationIssue {
  keyword: string;
  slugs: string[];
  severity: 'high' | 'medium' | 'low';
}

// ============= 150-GUIDE MASTER LIST =============

export const SCALING_GUIDES: ScalingGuide[] = [
  // ========== CLUSTER 1: CAT LITTER (50 guides) ==========
  // Week 1
  { slug: 'best-cat-litter-box-2026', title: 'Best Cat Litter Box (2026) – 12 Tested Picks for Odor Control, Large & Multi-Cat Homes', primaryKW: 'best cat litter box', secondaryKWs: ['cat litter box review', 'top litter boxes 2026', 'odor control litter box'], intent: 'commercial', priority: 100, cluster: 'cat-litter', week: 1, role: 'cornerstone', internalLinksTarget: 15, linksTo: ['how-many-litter-boxes-per-cat', 'best-litter-boxes-multi-cat', 'best-extra-large-litter-boxes'], difficulty: 'high' },
  { slug: 'how-many-litter-boxes-per-cat', title: 'How Many Litter Boxes Per Cat? The N+1 Rule Explained (2026)', primaryKW: 'how many litter boxes per cat', secondaryKWs: ['n+1 litter box rule', 'litter box per cat', 'multiple litter boxes'], intent: 'informational', priority: 95, cluster: 'cat-litter', week: 1, role: 'hub', internalLinksTarget: 10, linksTo: ['best-cat-litter-box-2026', 'best-litter-boxes-multi-cat'], difficulty: 'medium' },
  { slug: 'best-litter-boxes-multi-cat', title: 'Best Litter Boxes for Multiple Cats (2026) – Tested Picks With Pros & Cons', primaryKW: 'best litter box multi cat', secondaryKWs: ['litter box for 2 cats', 'multi cat litter box'], intent: 'commercial', priority: 90, cluster: 'cat-litter', week: 1, role: 'subguide', internalLinksTarget: 8, linksTo: ['best-cat-litter-box-2026', 'how-many-litter-boxes-per-cat'], difficulty: 'medium' },
  { slug: 'best-extra-large-litter-boxes', title: 'Best Extra Large Litter Boxes for Big Cats (2026) – Tested for Maine Coons', primaryKW: 'extra large litter box', secondaryKWs: ['xl litter box', 'litter box for maine coon', 'big litter box'], intent: 'commercial', priority: 88, cluster: 'cat-litter', week: 1, role: 'subguide', internalLinksTarget: 8, linksTo: ['best-cat-litter-box-2026', 'best-litter-box-maine-coon'], difficulty: 'medium' },
  // Week 2
  { slug: 'best-self-cleaning-litter-box-2026', title: 'Best Self-Cleaning Litter Boxes (2026) – Automatic Picks Tested & Reviewed', primaryKW: 'best self cleaning litter box', secondaryKWs: ['automatic litter box', 'self cleaning litter box review', 'robot litter box'], intent: 'commercial', priority: 92, cluster: 'cat-litter', week: 2, role: 'hub', internalLinksTarget: 10, linksTo: ['best-cat-litter-box-2026', 'litter-robot-vs-casa-leo'], difficulty: 'high' },
  { slug: 'best-covered-litter-box', title: 'Best Covered Litter Boxes (2026) – Hooded & Enclosed Picks for Odor Control', primaryKW: 'best covered litter box', secondaryKWs: ['hooded litter box', 'enclosed litter box', 'covered vs open litter box'], intent: 'commercial', priority: 82, cluster: 'cat-litter', week: 2, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-cat-litter-box-2026', 'covered-vs-open-litter-box'], difficulty: 'medium' },
  { slug: 'covered-vs-open-litter-box', title: 'Covered vs Open Litter Box – Which Is Better? Pros & Cons Compared', primaryKW: 'covered vs open litter box', secondaryKWs: ['hooded vs open cat box', 'enclosed vs open litter box'], intent: 'informational', priority: 78, cluster: 'cat-litter', week: 2, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-covered-litter-box', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'litter-robot-vs-casa-leo', title: 'Litter-Robot vs Casa Leo (2026) – Which Auto Litter Box Is Worth It?', primaryKW: 'litter robot vs casa leo', secondaryKWs: ['litter robot review', 'casa leo review', 'automatic litter box comparison'], intent: 'comparison', priority: 85, cluster: 'cat-litter', week: 2, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-self-cleaning-litter-box-2026', 'best-cat-litter-box-2026'], difficulty: 'medium' },
  // Week 3
  { slug: 'best-litter-box-odor-control', title: 'Best Litter Boxes for Odor Control (2026) – Tested in Real Homes', primaryKW: 'best litter box for odor control', secondaryKWs: ['odor free litter box', 'litter box smell solution', 'no smell litter box'], intent: 'commercial', priority: 86, cluster: 'cat-litter', week: 3, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-cat-litter-box-2026', 'best-covered-litter-box'], difficulty: 'medium' },
  { slug: 'best-litter-box-maine-coon', title: 'Best Litter Box for Maine Coons (2026) – Size Guide & Top Picks', primaryKW: 'best litter box for maine coon', secondaryKWs: ['maine coon litter box size', 'litter box for large breed cats'], intent: 'commercial', priority: 84, cluster: 'cat-litter', week: 3, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-extra-large-litter-boxes', 'best-cat-litter-box-2026'], difficulty: 'medium' },
  { slug: 'best-litter-box-kittens', title: 'Best Litter Boxes for Kittens (2026) – Safe Starter Picks With Low Entry', primaryKW: 'best litter box for kittens', secondaryKWs: ['kitten litter box', 'first litter box for kitten', 'kitten training litter box'], intent: 'commercial', priority: 75, cluster: 'cat-litter', week: 3, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026', 'how-many-litter-boxes-per-cat'], difficulty: 'low' },
  { slug: 'best-litter-box-senior-cats', title: 'Best Litter Boxes for Senior Cats (2026) – Low Entry & Arthritis-Friendly', primaryKW: 'best litter box for senior cats', secondaryKWs: ['low entry litter box', 'litter box for old cats', 'arthritis friendly litter box'], intent: 'commercial', priority: 73, cluster: 'cat-litter', week: 3, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026', 'best-extra-large-litter-boxes'], difficulty: 'low' },
  // Week 4
  { slug: 'best-stainless-steel-litter-box', title: 'Best Stainless Steel Litter Boxes (2026) – Durable, Odor-Free & Easy to Clean', primaryKW: 'stainless steel litter box', secondaryKWs: ['metal litter box', 'stainless cat box', 'non-stick litter box'], intent: 'commercial', priority: 76, cluster: 'cat-litter', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026', 'best-litter-box-odor-control'], difficulty: 'low' },
  { slug: 'best-top-entry-litter-box', title: 'Best Top-Entry Litter Boxes (2026) – Tested for Litter Tracking & Privacy', primaryKW: 'top entry litter box', secondaryKWs: ['top entry cat box', 'litter box less tracking', 'top entry vs side entry'], intent: 'commercial', priority: 74, cluster: 'cat-litter', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026', 'best-covered-litter-box'], difficulty: 'low' },
  { slug: 'best-disposable-litter-box', title: 'Best Disposable Litter Boxes (2026) – For Travel, Rescue & Temporary Use', primaryKW: 'disposable litter box', secondaryKWs: ['travel litter box', 'temporary cat box', 'biodegradable litter box'], intent: 'commercial', priority: 60, cluster: 'cat-litter', week: 4, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-under-50', title: 'Best Cat Litter Boxes Under $50 (2026) – Budget Picks That Don\'t Stink', primaryKW: 'best litter box under 50', secondaryKWs: ['cheap litter box', 'budget cat litter box', 'affordable litter box'], intent: 'commercial', priority: 72, cluster: 'cat-litter', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  // Week 5
  { slug: 'litter-box-placement-guide', title: 'Where to Put a Litter Box – Placement Guide for Every Home Layout', primaryKW: 'where to put litter box', secondaryKWs: ['litter box placement', 'best spot for litter box', 'litter box in bathroom'], intent: 'informational', priority: 70, cluster: 'cat-litter', week: 5, role: 'subguide', internalLinksTarget: 5, linksTo: ['how-many-litter-boxes-per-cat', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'how-to-stop-litter-tracking', title: 'How to Stop Litter Tracking – 7 Proven Tips & Best Mats Tested', primaryKW: 'how to stop litter tracking', secondaryKWs: ['litter tracking solutions', 'best litter mat', 'cat litter everywhere'], intent: 'informational', priority: 68, cluster: 'cat-litter', week: 5, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-top-entry-litter-box', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'clumping-vs-non-clumping-litter', title: 'Clumping vs Non-Clumping Litter – Which Is Better for Your Cat?', primaryKW: 'clumping vs non clumping litter', secondaryKWs: ['best type of cat litter', 'cat litter comparison'], intent: 'informational', priority: 65, cluster: 'cat-litter', week: 5, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-for-small-apartment', title: 'Best Litter Box for Small Apartments (2026) – Compact & Discreet Picks', primaryKW: 'best litter box for small apartment', secondaryKWs: ['compact litter box', 'small space litter box', 'apartment litter box'], intent: 'commercial', priority: 77, cluster: 'cat-litter', week: 5, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-cat-litter-box-furniture-enclosures-2026', 'best-cat-litter-box-2026'], difficulty: 'low' },
  // Week 6
  { slug: 'best-litter-box-for-spraying-cats', title: 'Best Litter Boxes for Cats That Spray (2026) – High-Sided Picks', primaryKW: 'litter box for spraying cats', secondaryKWs: ['high sided litter box', 'litter box for high pee'], intent: 'commercial', priority: 69, cluster: 'cat-litter', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-2026', 'best-covered-litter-box'], difficulty: 'low' },
  { slug: 'pine-vs-clay-litter', title: 'Pine vs Clay Cat Litter – Which Is Safer & More Effective?', primaryKW: 'pine vs clay cat litter', secondaryKWs: ['natural vs clay litter', 'best cat litter type'], intent: 'informational', priority: 58, cluster: 'cat-litter', week: 6, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026', 'clumping-vs-non-clumping-litter'], difficulty: 'low' },
  { slug: 'best-flushable-cat-litter', title: 'Best Flushable Cat Litter (2026) – Safe Picks for Toilet Disposal', primaryKW: 'best flushable cat litter', secondaryKWs: ['flushable litter', 'toilet safe cat litter', 'cat litter you can flush'], intent: 'commercial', priority: 62, cluster: 'cat-litter', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-2026', 'clumping-vs-non-clumping-litter'], difficulty: 'low' },
  { slug: 'best-dust-free-cat-litter', title: 'Best Dust-Free Cat Litter (2026) – Low Dust Picks for Allergies', primaryKW: 'best dust free cat litter', secondaryKWs: ['low dust cat litter', 'hypoallergenic cat litter', 'cat litter for asthma'], intent: 'commercial', priority: 64, cluster: 'cat-litter', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  // Week 7
  { slug: 'best-litter-box-mat', title: 'Best Litter Box Mats (2026) – Tested for Tracking & Easy Cleaning', primaryKW: 'best litter box mat', secondaryKWs: ['cat litter mat', 'litter trapping mat'], intent: 'commercial', priority: 67, cluster: 'cat-litter', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['how-to-stop-litter-tracking', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-automatic-litter-box-under-200', title: 'Best Automatic Litter Boxes Under $200 (2026) – Affordable Self-Cleaning', primaryKW: 'automatic litter box under 200', secondaryKWs: ['cheap self cleaning litter box', 'budget automatic litter box'], intent: 'commercial', priority: 71, cluster: 'cat-litter', week: 7, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-self-cleaning-litter-box-2026', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'litter-box-training-adult-cat', title: 'How to Litter Box Train an Adult Cat – Step-by-Step Guide', primaryKW: 'litter box training adult cat', secondaryKWs: ['teach cat to use litter box', 'cat litter box training'], intent: 'informational', priority: 56, cluster: 'cat-litter', week: 7, role: 'subguide', internalLinksTarget: 3, linksTo: ['how-many-litter-boxes-per-cat', 'best-cat-litter-box-2026'], difficulty: 'low' },
  // Week 8
  { slug: 'why-cat-peeing-outside-litter-box', title: 'Why Is My Cat Peeing Outside the Litter Box? 9 Causes & Fixes', primaryKW: 'cat peeing outside litter box', secondaryKWs: ['cat not using litter box', 'why does my cat pee everywhere'], intent: 'informational', priority: 64, cluster: 'cat-litter', week: 8, role: 'subguide', internalLinksTarget: 5, linksTo: ['how-many-litter-boxes-per-cat', 'litter-box-placement-guide', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-crystal-cat-litter', title: 'Best Crystal Cat Litter (2026) – Silica Gel Picks for Low Maintenance', primaryKW: 'best crystal cat litter', secondaryKWs: ['silica gel cat litter', 'crystal litter review'], intent: 'commercial', priority: 60, cluster: 'cat-litter', week: 8, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026', 'clumping-vs-non-clumping-litter'], difficulty: 'low' },
  // Week 9-10 (new cat litter expansion)
  { slug: 'best-corn-cat-litter', title: 'Best Corn Cat Litter (2026) – Natural & Biodegradable Picks', primaryKW: 'best corn cat litter', secondaryKWs: ['corn based cat litter', 'natural cat litter', 'worlds best cat litter review'], intent: 'commercial', priority: 55, cluster: 'cat-litter', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['clumping-vs-non-clumping-litter', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-lightweight-cat-litter', title: 'Best Lightweight Cat Litter (2026) – Easy Carry & Less Dust', primaryKW: 'best lightweight cat litter', secondaryKWs: ['light cat litter', 'lightweight clumping litter'], intent: 'commercial', priority: 58, cluster: 'cat-litter', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-deodorizer', title: 'Best Litter Box Deodorizers (2026) – Sprays, Powders & Carbon Filters', primaryKW: 'best litter box deodorizer', secondaryKWs: ['litter box smell remover', 'cat litter deodorizer spray', 'litter box odor eliminator'], intent: 'commercial', priority: 61, cluster: 'cat-litter', week: 9, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-litter-box-odor-control', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'how-often-change-cat-litter', title: 'How Often Should You Change Cat Litter? Complete Schedule Guide', primaryKW: 'how often change cat litter', secondaryKWs: ['cat litter change frequency', 'when to replace cat litter', 'how often scoop litter box'], intent: 'informational', priority: 63, cluster: 'cat-litter', week: 9, role: 'subguide', internalLinksTarget: 4, linksTo: ['how-many-litter-boxes-per-cat', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-liners', title: 'Best Litter Box Liners (2026) – Do They Work? Tested Options', primaryKW: 'best litter box liners', secondaryKWs: ['cat litter box liner', 'litter box bags', 'do litter box liners work'], intent: 'commercial', priority: 52, cluster: 'cat-litter', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-genie', title: 'Best Litter Genie Alternatives (2026) – Pail & Disposal Systems Compared', primaryKW: 'best litter genie alternative', secondaryKWs: ['litter disposal system', 'cat litter pail', 'litter genie vs diaper genie'], intent: 'commercial', priority: 57, cluster: 'cat-litter', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-litter-box-odor-control', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-for-bengal-cats', title: 'Best Litter Box for Bengal Cats (2026) – Large, Deep & Dig-Friendly', primaryKW: 'best litter box for bengal cats', secondaryKWs: ['bengal cat litter box', 'litter box for active cats'], intent: 'commercial', priority: 59, cluster: 'cat-litter', week: 10, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-extra-large-litter-boxes', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-for-ragdoll', title: 'Best Litter Box for Ragdolls (2026) – XL Picks for Fluffy Breeds', primaryKW: 'best litter box for ragdoll', secondaryKWs: ['ragdoll cat litter box', 'litter box for long hair cats'], intent: 'commercial', priority: 56, cluster: 'cat-litter', week: 10, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-extra-large-litter-boxes', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-for-obese-cats', title: 'Best Litter Box for Overweight Cats (2026) – Wide Entry & Sturdy Picks', primaryKW: 'best litter box for overweight cats', secondaryKWs: ['litter box for fat cats', 'large entry litter box', 'wide litter box'], intent: 'commercial', priority: 54, cluster: 'cat-litter', week: 10, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-extra-large-litter-boxes', 'best-cat-litter-box-2026'], difficulty: 'low' },
  // Week 11-12 cat litter
  { slug: 'best-smart-litter-box', title: 'Best Smart Litter Boxes With App (2026) – WiFi Connected Picks', primaryKW: 'best smart litter box', secondaryKWs: ['wifi litter box', 'litter box with app', 'smart cat litter box'], intent: 'commercial', priority: 66, cluster: 'cat-litter', week: 11, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-self-cleaning-litter-box-2026', 'best-cat-litter-box-2026'], difficulty: 'medium' },
  { slug: 'cat-litter-box-smell-solutions', title: 'Cat Litter Box Smell Solutions – 10 Tips That Actually Work', primaryKW: 'cat litter box smell solution', secondaryKWs: ['how to reduce litter box smell', 'litter box stinks', 'eliminate cat litter odor'], intent: 'informational', priority: 63, cluster: 'cat-litter', week: 11, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-litter-box-odor-control', 'best-litter-box-deodorizer'], difficulty: 'low' },
  { slug: 'sifting-litter-box-guide', title: 'Best Sifting Litter Boxes (2026) – Easy Clean Picks Tested', primaryKW: 'best sifting litter box', secondaryKWs: ['sifting cat litter box', 'litter box with sifter'], intent: 'commercial', priority: 55, cluster: 'cat-litter', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-with-lid', title: 'Best Litter Boxes With Lid (2026) – Tested for Privacy & Odor', primaryKW: 'best litter box with lid', secondaryKWs: ['litter box with top', 'closed litter box', 'litter box with cover'], intent: 'commercial', priority: 57, cluster: 'cat-litter', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-covered-litter-box', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-corner-litter-box', title: 'Best Corner Litter Boxes (2026) – Space-Saving Triangle Picks', primaryKW: 'best corner litter box', secondaryKWs: ['triangle litter box', 'corner cat litter box', 'space saving litter box'], intent: 'commercial', priority: 53, cluster: 'cat-litter', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-litter-box-for-small-apartment', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-litter-box-for-persian-cats', title: 'Best Litter Box for Persian Cats (2026) – Low Entry & Long-Hair Friendly', primaryKW: 'best litter box for persian cats', secondaryKWs: ['persian cat litter box', 'litter box for flat face cats'], intent: 'commercial', priority: 51, cluster: 'cat-litter', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026', 'best-litter-box-senior-cats'], difficulty: 'low' },

  // ========== CLUSTER 2: CAT FURNITURE (40 guides) ==========
  // Week 1
  { slug: 'best-cat-litter-box-furniture-enclosures-2026', title: 'Best Cat Litter Box Furniture & Enclosures (2026) – Reviewed & Tested', primaryKW: 'cat litter box furniture', secondaryKWs: ['litter box enclosure', 'hidden litter box', 'litter box cabinet'], intent: 'commercial', priority: 93, cluster: 'cat-furniture', week: 1, role: 'cornerstone', internalLinksTarget: 12, linksTo: ['best-cat-litter-box-2026', 'best-cat-trees-small-apartments'], difficulty: 'high' },
  { slug: 'best-cat-trees-small-apartments', title: 'Best Cat Trees for Small Apartments (2026) – Space-Saving Picks, Tested', primaryKW: 'best cat tree small apartment', secondaryKWs: ['compact cat tree', 'small space cat tree', 'apartment cat tree'], intent: 'commercial', priority: 91, cluster: 'cat-furniture', week: 1, role: 'hub', internalLinksTarget: 10, linksTo: ['best-cat-litter-box-furniture-enclosures-2026', 'best-wall-mounted-cat-shelves'], difficulty: 'medium' },
  // Week 2
  { slug: 'best-cat-tree-maine-coon', title: 'Best Cat Trees for Maine Coons (2026) – Heavy-Duty Tested Picks', primaryKW: 'best cat tree for maine coon', secondaryKWs: ['large cat tree', 'heavy duty cat tree', 'cat tree for big cats'], intent: 'commercial', priority: 87, cluster: 'cat-furniture', week: 2, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-cat-trees-small-apartments', 'best-cat-litter-box-furniture-enclosures-2026'], difficulty: 'medium' },
  { slug: 'best-wall-mounted-cat-shelves', title: 'Best Wall-Mounted Cat Shelves (2026) – Modern Picks for Active Cats', primaryKW: 'wall mounted cat shelves', secondaryKWs: ['cat wall furniture', 'cat climbing wall', 'cat shelves for wall'], intent: 'commercial', priority: 80, cluster: 'cat-furniture', week: 2, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'medium' },
  { slug: 'best-cat-window-perch', title: 'Best Cat Window Perches (2026) – Suction Cup & Mounted Options Tested', primaryKW: 'best cat window perch', secondaryKWs: ['cat window shelf', 'cat window seat', 'suction cup cat perch'], intent: 'commercial', priority: 75, cluster: 'cat-furniture', week: 2, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'low' },
  // Week 3
  { slug: 'best-cat-scratching-post', title: 'Best Cat Scratching Posts (2026) – Tested for Durability & Cats That Shred', primaryKW: 'best cat scratching post', secondaryKWs: ['cat scratcher', 'tall scratching post', 'sisal scratching post'], intent: 'commercial', priority: 83, cluster: 'cat-furniture', week: 3, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-cat-trees-small-apartments', 'best-cat-litter-box-furniture-enclosures-2026'], difficulty: 'medium' },
  { slug: 'best-cat-condo-2026', title: 'Best Cat Condos (2026) – Multi-Level Picks for Play & Rest', primaryKW: 'best cat condo', secondaryKWs: ['cat condo tower', 'multi level cat condo', 'cat condo with hammock'], intent: 'commercial', priority: 81, cluster: 'cat-furniture', week: 3, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'medium' },
  { slug: 'cat-tree-vs-cat-condo', title: 'Cat Tree vs Cat Condo – What\'s the Difference & Which Is Better?', primaryKW: 'cat tree vs cat condo', secondaryKWs: ['difference cat tree condo', 'cat tree or condo'], intent: 'informational', priority: 65, cluster: 'cat-furniture', week: 3, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-condo-2026', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  // Week 4
  { slug: 'best-modern-cat-furniture', title: 'Best Modern Cat Furniture (2026) – Minimalist & Stylish Picks', primaryKW: 'modern cat furniture', secondaryKWs: ['minimalist cat furniture', 'stylish cat tree', 'designer cat furniture'], intent: 'commercial', priority: 74, cluster: 'cat-furniture', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-furniture-enclosures-2026', 'best-cat-trees-small-apartments'], difficulty: 'medium' },
  { slug: 'best-cat-tree-under-100', title: 'Best Cat Trees Under $100 (2026) – Budget Picks That Last', primaryKW: 'best cat tree under 100', secondaryKWs: ['cheap cat tree', 'affordable cat tree', 'budget cat tree'], intent: 'commercial', priority: 76, cluster: 'cat-furniture', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-cat-hammock', title: 'Best Cat Hammocks (2026) – Window, Wall & Free-Standing Picks', primaryKW: 'best cat hammock', secondaryKWs: ['cat hammock bed', 'hanging cat bed', 'cat hammock for window'], intent: 'commercial', priority: 68, cluster: 'cat-furniture', week: 4, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-window-perch', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  // Week 5
  { slug: 'best-cat-tree-for-2-cats', title: 'Best Cat Trees for 2 Cats (2026) – Multi-Cat Tested Picks', primaryKW: 'best cat tree for 2 cats', secondaryKWs: ['cat tree for two cats', 'multi cat tree', 'cat tree multiple cats'], intent: 'commercial', priority: 73, cluster: 'cat-furniture', week: 5, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-trees-small-apartments', 'best-litter-boxes-multi-cat'], difficulty: 'low' },
  { slug: 'best-outdoor-cat-enclosure', title: 'Best Outdoor Cat Enclosures (2026) – Catios Tested for Safety & Space', primaryKW: 'outdoor cat enclosure', secondaryKWs: ['catio', 'outdoor cat pen', 'cat patio enclosure'], intent: 'commercial', priority: 70, cluster: 'cat-furniture', week: 5, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'medium' },
  { slug: 'best-cat-bed-2026', title: 'Best Cat Beds (2026) – Cozy Picks Tested by Real Cat Owners', primaryKW: 'best cat bed', secondaryKWs: ['cat bed review', 'heated cat bed', 'calming cat bed'], intent: 'commercial', priority: 72, cluster: 'cat-furniture', week: 5, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'low' },
  // Week 6
  { slug: 'how-to-get-cat-to-use-cat-tree', title: 'How to Get Your Cat to Use a Cat Tree – 8 Proven Tips', primaryKW: 'how to get cat to use cat tree', secondaryKWs: ['cat ignores cat tree', 'cat tree training'], intent: 'informational', priority: 62, cluster: 'cat-furniture', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-trees-small-apartments', 'best-cat-scratching-post'], difficulty: 'low' },
  { slug: 'best-cat-tree-with-litter-box', title: 'Best Cat Trees With Built-In Litter Box Enclosure (2026)', primaryKW: 'cat tree with litter box', secondaryKWs: ['cat tree litter box combo', 'all in one cat furniture'], intent: 'commercial', priority: 71, cluster: 'cat-furniture', week: 6, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-cat-litter-box-furniture-enclosures-2026', 'best-cat-trees-small-apartments'], difficulty: 'medium' },
  { slug: 'best-floor-to-ceiling-cat-tree', title: 'Best Floor-to-Ceiling Cat Trees (2026) – Tall Picks for Climbers', primaryKW: 'floor to ceiling cat tree', secondaryKWs: ['tall cat tree', 'ceiling height cat tree'], intent: 'commercial', priority: 66, cluster: 'cat-furniture', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-trees-small-apartments', 'best-cat-tree-maine-coon'], difficulty: 'low' },
  // Week 7
  { slug: 'best-cat-tree-for-heavy-cats', title: 'Best Cat Trees for Heavy Cats (2026) – Sturdy Picks for 15+ lb Cats', primaryKW: 'cat tree for heavy cats', secondaryKWs: ['sturdy cat tree', 'cat tree weight limit', 'cat tree for fat cats'], intent: 'commercial', priority: 69, cluster: 'cat-furniture', week: 7, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-tree-maine-coon', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-cat-tunnel', title: 'Best Cat Tunnels (2026) – Crinkle, Pop-Up & Interactive Picks', primaryKW: 'best cat tunnel', secondaryKWs: ['cat play tunnel', 'crinkle cat tunnel'], intent: 'commercial', priority: 58, cluster: 'cat-furniture', week: 7, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'low' },
  // Week 8
  { slug: 'best-cat-feeding-station', title: 'Best Cat Feeding Stations (2026) – Elevated & Multi-Cat Tested', primaryKW: 'best cat feeding station', secondaryKWs: ['raised cat bowl', 'elevated cat feeder', 'cat feeding stand'], intent: 'commercial', priority: 61, cluster: 'cat-furniture', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-furniture-enclosures-2026'], difficulty: 'low' },
  { slug: 'best-cat-tree-with-hammock', title: 'Best Cat Trees With Hammock (2026) – Cozy & Fun Picks Tested', primaryKW: 'cat tree with hammock', secondaryKWs: ['cat tree hammock bed', 'cat tree with hanging bed'], intent: 'commercial', priority: 63, cluster: 'cat-furniture', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-trees-small-apartments', 'best-cat-condo-2026'], difficulty: 'low' },
  { slug: 'best-sisal-cat-scratcher', title: 'Best Sisal Cat Scratchers (2026) – Post, Board & Pad Picks', primaryKW: 'best sisal cat scratcher', secondaryKWs: ['sisal scratching post', 'sisal vs cardboard scratcher'], intent: 'commercial', priority: 59, cluster: 'cat-furniture', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-scratching-post', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  // Week 9-12 (new cat furniture expansion)
  { slug: 'best-cat-door-for-interior', title: 'Best Cat Doors for Interior Doors (2026) – Easy Install Picks', primaryKW: 'best cat door interior', secondaryKWs: ['cat flap for door', 'interior cat door', 'pet door for cats'], intent: 'commercial', priority: 60, cluster: 'cat-furniture', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-furniture-enclosures-2026'], difficulty: 'low' },
  { slug: 'best-cat-stairs-for-bed', title: 'Best Cat Stairs & Steps for Bed (2026) – Senior & Kitten Friendly', primaryKW: 'best cat stairs for bed', secondaryKWs: ['cat steps for bed', 'pet stairs for cats', 'cat ramp for bed'], intent: 'commercial', priority: 57, cluster: 'cat-furniture', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-bed-2026'], difficulty: 'low' },
  { slug: 'best-cat-tower-2026', title: 'Best Cat Towers (2026) – Tall, Multi-Level Picks for Active Cats', primaryKW: 'best cat tower', secondaryKWs: ['cat tower review', 'multi level cat tower', 'tall cat tower'], intent: 'commercial', priority: 65, cluster: 'cat-furniture', week: 9, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-trees-small-apartments', 'best-cat-condo-2026'], difficulty: 'low' },
  { slug: 'best-cat-playpen', title: 'Best Cat Playpens (2026) – Indoor Enclosures for Kittens & Recovery', primaryKW: 'best cat playpen', secondaryKWs: ['cat enclosure indoor', 'kitten playpen', 'cat recovery cage'], intent: 'commercial', priority: 54, cluster: 'cat-furniture', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-outdoor-cat-enclosure'], difficulty: 'low' },
  { slug: 'best-cat-shelves-ikea-hack', title: 'Best Cat Shelves IKEA Hacks (2026) – Budget DIY Wall Climbers', primaryKW: 'cat shelves ikea hack', secondaryKWs: ['diy cat wall', 'ikea cat furniture', 'cat climbing wall diy'], intent: 'informational', priority: 56, cluster: 'cat-furniture', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-wall-mounted-cat-shelves', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-cat-exercise-wheel', title: 'Best Cat Exercise Wheels (2026) – Tested for Safety & Fun', primaryKW: 'best cat exercise wheel', secondaryKWs: ['cat running wheel', 'cat wheel review', 'cat treadmill wheel'], intent: 'commercial', priority: 62, cluster: 'cat-furniture', week: 11, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'medium' },
  { slug: 'best-heated-cat-bed', title: 'Best Heated Cat Beds (2026) – Self-Warming & Electric Picks', primaryKW: 'best heated cat bed', secondaryKWs: ['self warming cat bed', 'electric cat bed', 'winter cat bed'], intent: 'commercial', priority: 60, cluster: 'cat-furniture', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-bed-2026'], difficulty: 'low' },
  { slug: 'best-cat-carrier-2026', title: 'Best Cat Carriers (2026) – Airline Approved & Vet-Visit Ready', primaryKW: 'best cat carrier', secondaryKWs: ['cat carrier for vet', 'airline approved cat carrier', 'soft cat carrier'], intent: 'commercial', priority: 64, cluster: 'cat-furniture', week: 12, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-furniture-enclosures-2026'], difficulty: 'low' },
  { slug: 'best-cat-backpack-carrier', title: 'Best Cat Backpack Carriers (2026) – Bubble & Mesh Picks for Adventures', primaryKW: 'best cat backpack carrier', secondaryKWs: ['cat backpack', 'bubble cat backpack', 'cat carrier backpack'], intent: 'commercial', priority: 58, cluster: 'cat-furniture', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-carrier-2026'], difficulty: 'low' },

  // ========== CLUSTER 3: DOG BEDS (30 guides) ==========
  // Week 3
  { slug: 'best-dog-bed-2026', title: 'Best Dog Beds (2026) – 10 Tested Picks for Every Breed & Budget', primaryKW: 'best dog bed', secondaryKWs: ['dog bed review', 'top dog beds 2026', 'comfortable dog bed'], intent: 'commercial', priority: 95, cluster: 'dog-beds', week: 3, role: 'cornerstone', internalLinksTarget: 12, linksTo: ['best-orthopedic-dog-bed', 'best-dog-bed-large-dogs'], difficulty: 'high' },
  { slug: 'best-orthopedic-dog-bed', title: 'Best Orthopedic Dog Beds (2026) – Tested for Joint Support & Comfort', primaryKW: 'best orthopedic dog bed', secondaryKWs: ['memory foam dog bed', 'dog bed for arthritis', 'joint support dog bed'], intent: 'commercial', priority: 88, cluster: 'dog-beds', week: 3, role: 'hub', internalLinksTarget: 8, linksTo: ['best-dog-bed-2026', 'best-dog-bed-senior-dogs'], difficulty: 'medium' },
  // Week 4
  { slug: 'best-dog-bed-large-dogs', title: 'Best Dog Beds for Large Dogs (2026) – XL Picks for 50–100+ lbs', primaryKW: 'best dog bed for large dogs', secondaryKWs: ['xl dog bed', 'big dog bed', 'dog bed for 100 lb dog'], intent: 'commercial', priority: 86, cluster: 'dog-beds', week: 4, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-dog-bed-2026', 'best-orthopedic-dog-bed'], difficulty: 'medium' },
  { slug: 'best-dog-bed-senior-dogs', title: 'Best Dog Beds for Senior Dogs (2026) – Comfort & Easy Access Tested', primaryKW: 'best dog bed for senior dogs', secondaryKWs: ['old dog bed', 'dog bed for aging dogs', 'heated dog bed for seniors'], intent: 'commercial', priority: 80, cluster: 'dog-beds', week: 4, role: 'subguide', internalLinksTarget: 6, linksTo: ['best-orthopedic-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-calming-dog-bed', title: 'Best Calming Dog Beds (2026) – Anxiety Relief Picks Tested', primaryKW: 'best calming dog bed', secondaryKWs: ['anti anxiety dog bed', 'donut dog bed', 'dog bed for anxious dogs'], intent: 'commercial', priority: 78, cluster: 'dog-beds', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  // Week 5
  { slug: 'best-chew-proof-dog-bed', title: 'Best Chew-Proof Dog Beds (2026) – Indestructible Picks for Heavy Chewers', primaryKW: 'best chew proof dog bed', secondaryKWs: ['indestructible dog bed', 'dog bed for chewers', 'durable dog bed'], intent: 'commercial', priority: 77, cluster: 'dog-beds', week: 5, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-dog-bed-2026', 'best-dog-bed-large-dogs'], difficulty: 'low' },
  { slug: 'best-elevated-dog-bed', title: 'Best Elevated Dog Beds (2026) – Cooling Cot Picks for Summer', primaryKW: 'best elevated dog bed', secondaryKWs: ['raised dog bed', 'dog cot', 'cooling dog bed'], intent: 'commercial', priority: 72, cluster: 'dog-beds', week: 5, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-crate-bed', title: 'Best Dog Crate Beds & Mats (2026) – Perfect Fit Picks Tested', primaryKW: 'best dog crate bed', secondaryKWs: ['crate pad', 'crate mat for dogs', 'dog bed for kennel'], intent: 'commercial', priority: 70, cluster: 'dog-beds', week: 5, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  // Week 6
  { slug: 'best-dog-bed-under-50', title: 'Best Dog Beds Under $50 (2026) – Budget Picks That Actually Last', primaryKW: 'best dog bed under 50', secondaryKWs: ['cheap dog bed', 'affordable dog bed', 'budget dog bed'], intent: 'commercial', priority: 74, cluster: 'dog-beds', week: 6, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-waterproof-dog-bed', title: 'Best Waterproof Dog Beds (2026) – For Puppies, Seniors & Outdoor Use', primaryKW: 'best waterproof dog bed', secondaryKWs: ['waterproof dog bed cover', 'dog bed for incontinence'], intent: 'commercial', priority: 68, cluster: 'dog-beds', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026', 'best-dog-bed-senior-dogs'], difficulty: 'low' },
  { slug: 'memory-foam-vs-bolster-dog-bed', title: 'Memory Foam vs Bolster Dog Bed – Which Is Better for Your Dog?', primaryKW: 'memory foam vs bolster dog bed', secondaryKWs: ['dog bed comparison', 'flat vs bolster dog bed'], intent: 'informational', priority: 60, cluster: 'dog-beds', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-orthopedic-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  // Week 7
  { slug: 'best-dog-bed-golden-retriever', title: 'Best Dog Beds for Golden Retrievers (2026) – Breed-Specific Picks', primaryKW: 'best dog bed for golden retriever', secondaryKWs: ['golden retriever bed size', 'bed for golden retriever'], intent: 'commercial', priority: 65, cluster: 'dog-beds', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-large-dogs', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-french-bulldog', title: 'Best Dog Beds for French Bulldogs (2026) – Flat-Nose Friendly Picks', primaryKW: 'best dog bed for french bulldog', secondaryKWs: ['french bulldog bed', 'bed for brachycephalic dogs'], intent: 'commercial', priority: 63, cluster: 'dog-beds', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-heated-dog-bed', title: 'Best Heated Dog Beds (2026) – Safe Warming Picks for Cold Weather', primaryKW: 'best heated dog bed', secondaryKWs: ['self warming dog bed', 'electric dog bed', 'winter dog bed'], intent: 'commercial', priority: 66, cluster: 'dog-beds', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026', 'best-dog-bed-senior-dogs'], difficulty: 'low' },
  // Week 8
  { slug: 'best-outdoor-dog-bed', title: 'Best Outdoor Dog Beds (2026) – Weather-Resistant Picks Tested', primaryKW: 'best outdoor dog bed', secondaryKWs: ['outside dog bed', 'patio dog bed', 'weather resistant dog bed'], intent: 'commercial', priority: 64, cluster: 'dog-beds', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026', 'best-elevated-dog-bed'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-car', title: 'Best Dog Beds for Car Travel (2026) – Safe & Comfortable Road Trip Picks', primaryKW: 'best dog bed for car', secondaryKWs: ['car dog bed', 'travel dog bed', 'dog car seat bed'], intent: 'commercial', priority: 62, cluster: 'dog-beds', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'how-to-wash-dog-bed', title: 'How to Wash a Dog Bed – Complete Cleaning Guide for Every Material', primaryKW: 'how to wash dog bed', secondaryKWs: ['clean dog bed', 'dog bed washing instructions', 'sanitize dog bed'], intent: 'informational', priority: 55, cluster: 'dog-beds', week: 8, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  // Week 9-12 (new dog bed expansion)
  { slug: 'best-dog-bed-german-shepherd', title: 'Best Dog Beds for German Shepherds (2026) – Breed-Specific Picks', primaryKW: 'best dog bed for german shepherd', secondaryKWs: ['german shepherd bed', 'large breed dog bed'], intent: 'commercial', priority: 61, cluster: 'dog-beds', week: 9, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-large-dogs', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-labrador', title: 'Best Dog Beds for Labradors (2026) – Durable Picks for Active Labs', primaryKW: 'best dog bed for labrador', secondaryKWs: ['labrador bed', 'dog bed for labs'], intent: 'commercial', priority: 60, cluster: 'dog-beds', week: 9, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-large-dogs', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-dachshund', title: 'Best Dog Beds for Dachshunds (2026) – Back Support & Low Entry', primaryKW: 'best dog bed for dachshund', secondaryKWs: ['dachshund bed', 'wiener dog bed', 'long dog bed'], intent: 'commercial', priority: 58, cluster: 'dog-beds', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-orthopedic-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-puppy', title: 'Best Dog Beds for Puppies (2026) – Chew-Safe & Washable Picks', primaryKW: 'best dog bed for puppy', secondaryKWs: ['puppy bed', 'dog bed for puppies', 'puppy crate bed'], intent: 'commercial', priority: 66, cluster: 'dog-beds', week: 10, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026', 'best-chew-proof-dog-bed'], difficulty: 'low' },
  { slug: 'best-cooling-dog-bed', title: 'Best Cooling Dog Beds (2026) – Gel, Water & Elevated Picks', primaryKW: 'best cooling dog bed', secondaryKWs: ['cooling mat for dogs', 'gel dog bed', 'summer dog bed'], intent: 'commercial', priority: 64, cluster: 'dog-beds', week: 11, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-elevated-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-sofa-bed', title: 'Best Dog Sofa Beds (2026) – Couch-Style Picks for Spoiled Pups', primaryKW: 'best dog sofa bed', secondaryKWs: ['dog couch bed', 'luxury dog bed', 'dog sofa'], intent: 'commercial', priority: 59, cluster: 'dog-beds', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-with-removable-cover', title: 'Best Dog Beds With Removable Cover (2026) – Washable & Easy Clean', primaryKW: 'best dog bed removable cover', secondaryKWs: ['washable dog bed', 'dog bed with cover', 'easy clean dog bed'], intent: 'commercial', priority: 62, cluster: 'dog-beds', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-2026', 'how-to-wash-dog-bed'], difficulty: 'low' },

  // ========== CLUSTER 4: MICRO-INTENT (30 guides) ==========
  // Breed/size/problem-specific long-tail content
  // Week 5-12 distributed
  { slug: 'why-does-my-cat-scratch-furniture', title: 'Why Does My Cat Scratch Furniture? 6 Reasons & Solutions', primaryKW: 'why does my cat scratch furniture', secondaryKWs: ['cat scratching furniture solution', 'how to stop cat scratching couch'], intent: 'informational', priority: 55, cluster: 'micro-intent', week: 5, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-scratching-post', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'how-to-introduce-second-litter-box', title: 'How to Introduce a Second Litter Box – Multi-Cat Transition Guide', primaryKW: 'how to introduce second litter box', secondaryKWs: ['adding litter box for second cat', 'second litter box placement'], intent: 'informational', priority: 52, cluster: 'micro-intent', week: 5, role: 'subguide', internalLinksTarget: 3, linksTo: ['how-many-litter-boxes-per-cat', 'best-litter-boxes-multi-cat'], difficulty: 'low' },
  { slug: 'cat-not-covering-poop', title: 'Why Is My Cat Not Covering Their Poop? Causes & Solutions', primaryKW: 'cat not covering poop', secondaryKWs: ['cat doesnt bury poop', 'why my cat wont cover feces'], intent: 'informational', priority: 48, cluster: 'micro-intent', week: 6, role: 'subguide', internalLinksTarget: 3, linksTo: ['how-many-litter-boxes-per-cat', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-cat-tree-for-older-cats', title: 'Best Cat Trees for Older Cats (2026) – Low Platforms & Easy Climb', primaryKW: 'best cat tree for older cats', secondaryKWs: ['senior cat tree', 'cat tree for aging cats', 'low cat tree'], intent: 'commercial', priority: 56, cluster: 'micro-intent', week: 6, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-trees-small-apartments', 'best-litter-box-senior-cats'], difficulty: 'low' },
  { slug: 'best-litter-for-declawed-cats', title: 'Best Cat Litter for Declawed Cats (2026) – Soft & Gentle Picks', primaryKW: 'best litter for declawed cats', secondaryKWs: ['soft cat litter', 'gentle litter for sensitive paws'], intent: 'commercial', priority: 50, cluster: 'micro-intent', week: 7, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'indoor-vs-outdoor-cat-guide', title: 'Indoor vs Outdoor Cat – Pros, Cons & How to Decide', primaryKW: 'indoor vs outdoor cat', secondaryKWs: ['should my cat go outside', 'indoor cat vs outdoor cat pros cons'], intent: 'informational', priority: 53, cluster: 'micro-intent', week: 7, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-outdoor-cat-enclosure', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'dog-bed-size-guide', title: 'Dog Bed Size Guide – How to Measure & Pick the Right Size', primaryKW: 'dog bed size guide', secondaryKWs: ['what size dog bed', 'how to measure dog for bed', 'dog bed dimensions'], intent: 'informational', priority: 58, cluster: 'micro-intent', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026', 'best-dog-bed-large-dogs'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-hip-dysplasia', title: 'Best Dog Beds for Hip Dysplasia (2026) – Vet-Recommended Picks', primaryKW: 'best dog bed for hip dysplasia', secondaryKWs: ['dog bed for joint problems', 'hip dysplasia dog bed'], intent: 'commercial', priority: 57, cluster: 'micro-intent', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-orthopedic-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'cat-litter-box-for-rv', title: 'Best Cat Litter Box for RV & Travel (2026) – Compact & Spill-Proof', primaryKW: 'cat litter box for rv', secondaryKWs: ['travel cat litter box', 'rv cat litter solution', 'portable litter box'], intent: 'commercial', priority: 49, cluster: 'micro-intent', week: 8, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-disposable-litter-box', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'how-to-keep-dog-off-bed', title: 'How to Keep Your Dog Off the Bed – 5 Trainer-Approved Tips', primaryKW: 'how to keep dog off bed', secondaryKWs: ['dog wont stay off bed', 'stop dog sleeping on bed'], intent: 'informational', priority: 47, cluster: 'micro-intent', week: 8, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'litter-box-for-disabled-cats', title: 'Best Litter Box for Disabled Cats (2026) – Accessible & Easy Entry', primaryKW: 'litter box for disabled cats', secondaryKWs: ['accessible cat litter box', 'litter box for handicapped cat'], intent: 'commercial', priority: 45, cluster: 'micro-intent', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-litter-box-senior-cats', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-cat-tree-for-bengal', title: 'Best Cat Trees for Bengal Cats (2026) – Active & Tall Picks', primaryKW: 'best cat tree for bengal', secondaryKWs: ['bengal cat tree', 'cat tree for active cats'], intent: 'commercial', priority: 54, cluster: 'micro-intent', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-trees-small-apartments', 'best-floor-to-ceiling-cat-tree'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-poodle', title: 'Best Dog Beds for Poodles (2026) – Standard, Mini & Toy Sizes', primaryKW: 'best dog bed for poodle', secondaryKWs: ['poodle bed', 'standard poodle dog bed'], intent: 'commercial', priority: 50, cluster: 'micro-intent', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'how-to-transition-cat-litter', title: 'How to Switch Cat Litter Without Issues – Step-by-Step Guide', primaryKW: 'how to transition cat litter', secondaryKWs: ['switch cat litter', 'change cat litter type', 'cat litter transition'], intent: 'informational', priority: 48, cluster: 'micro-intent', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['clumping-vs-non-clumping-litter', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-bulldogs', title: 'Best Dog Beds for Bulldogs (2026) – English & American Breed Picks', primaryKW: 'best dog bed for bulldogs', secondaryKWs: ['english bulldog bed', 'bulldog dog bed'], intent: 'commercial', priority: 52, cluster: 'micro-intent', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'cat-tree-for-small-kittens', title: 'Best Cat Trees for Small Kittens (2026) – Safe & Low-Height Picks', primaryKW: 'cat tree for small kittens', secondaryKWs: ['kitten cat tree', 'small cat tree for kittens', 'low cat tree for kittens'], intent: 'commercial', priority: 53, cluster: 'micro-intent', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-corgis', title: 'Best Dog Beds for Corgis (2026) – Low Entry & Back Support', primaryKW: 'best dog bed for corgi', secondaryKWs: ['corgi bed', 'corgi dog bed'], intent: 'commercial', priority: 49, cluster: 'micro-intent', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-orthopedic-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'cat-furniture-for-multiple-cats', title: 'Best Cat Furniture for Multiple Cats (2026) – Space & Play Picks', primaryKW: 'cat furniture for multiple cats', secondaryKWs: ['multi cat furniture', 'cat furniture for 3 cats'], intent: 'commercial', priority: 55, cluster: 'micro-intent', week: 11, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-tree-for-2-cats', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-huskies', title: 'Best Dog Beds for Huskies (2026) – Cooling & Durable Picks', primaryKW: 'best dog bed for husky', secondaryKWs: ['husky dog bed', 'dog bed for husky'], intent: 'commercial', priority: 51, cluster: 'micro-intent', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-large-dogs', 'best-cooling-dog-bed'], difficulty: 'low' },
  { slug: 'best-cat-tree-for-ragdoll', title: 'Best Cat Trees for Ragdoll Cats (2026) – Sturdy & Comfortable', primaryKW: 'best cat tree for ragdoll', secondaryKWs: ['ragdoll cat tree', 'cat tree for large fluffy cats'], intent: 'commercial', priority: 52, cluster: 'micro-intent', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-tree-maine-coon', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-boxers', title: 'Best Dog Beds for Boxers (2026) – Supportive Picks for Active Breeds', primaryKW: 'best dog bed for boxer', secondaryKWs: ['boxer dog bed', 'dog bed for boxer'], intent: 'commercial', priority: 48, cluster: 'micro-intent', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dog-bed-large-dogs', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'litter-box-solutions-for-basement', title: 'Litter Box in Basement – Pros, Cons & Setup Tips', primaryKW: 'litter box in basement', secondaryKWs: ['basement litter box setup', 'litter box downstairs'], intent: 'informational', priority: 44, cluster: 'micro-intent', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['litter-box-placement-guide', 'how-many-litter-boxes-per-cat'], difficulty: 'low' },
  { slug: 'best-cat-tree-for-siamese', title: 'Best Cat Trees for Siamese Cats (2026) – Playful & Tall Picks', primaryKW: 'best cat tree for siamese', secondaryKWs: ['siamese cat tree', 'cat tree for vocal cats'], intent: 'commercial', priority: 47, cluster: 'micro-intent', week: 12, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-trees-small-apartments', 'best-floor-to-ceiling-cat-tree'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-great-dane', title: 'Best Dog Beds for Great Danes (2026) – Giant Size Picks Tested', primaryKW: 'best dog bed for great dane', secondaryKWs: ['great dane bed', 'xxl dog bed', 'giant breed dog bed'], intent: 'commercial', priority: 55, cluster: 'micro-intent', week: 12, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-large-dogs', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'how-to-stop-cat-from-peeing-on-bed', title: 'How to Stop Your Cat From Peeing on the Bed – 7 Vet Tips', primaryKW: 'how to stop cat peeing on bed', secondaryKWs: ['cat peeing on bed', 'why does my cat pee on my bed'], intent: 'informational', priority: 53, cluster: 'micro-intent', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['why-cat-peeing-outside-litter-box', 'how-many-litter-boxes-per-cat'], difficulty: 'low' },
  { slug: 'diy-cat-tree-guide', title: 'How to Build a DIY Cat Tree – Simple Plans & Materials Guide', primaryKW: 'diy cat tree', secondaryKWs: ['build cat tree', 'homemade cat tree', 'cat tree plans'], intent: 'informational', priority: 50, cluster: 'micro-intent', week: 10, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-trees-small-apartments', 'best-cat-tree-under-100'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-small-dogs', title: 'Best Dog Beds for Small Dogs (2026) – Cozy Picks for Under 20 lbs', primaryKW: 'best dog bed for small dogs', secondaryKWs: ['small dog bed', 'dog bed for tiny dogs', 'mini dog bed'], intent: 'commercial', priority: 62, cluster: 'micro-intent', week: 9, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-dog-bed-2026', 'best-calming-dog-bed'], difficulty: 'low' },
  { slug: 'best-cat-tree-under-50', title: 'Best Cat Trees Under $50 (2026) – Cheap But Good Picks', primaryKW: 'best cat tree under 50', secondaryKWs: ['cheapest cat tree', 'cat tree under 50 dollars'], intent: 'commercial', priority: 56, cluster: 'micro-intent', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-cat-tree-under-100', 'best-cat-trees-small-apartments'], difficulty: 'low' },
  { slug: 'best-litter-box-for-sphynx', title: 'Best Litter Box for Sphynx Cats (2026) – Low Dust & Warm Entry', primaryKW: 'best litter box for sphynx cat', secondaryKWs: ['sphynx cat litter box', 'litter for hairless cats'], intent: 'commercial', priority: 46, cluster: 'micro-intent', week: 11, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-dust-free-cat-litter', 'best-cat-litter-box-2026'], difficulty: 'low' },

  // ========== CLUSTER 5: DOG TRAINING (10 guides) ==========
  // Pillar
  { slug: 'complete-dog-training-guide-2026', title: 'The Complete Dog Training Guide (2026) – Stop Pulling, Barking & Bad Habits Fast', primaryKW: 'dog training guide', secondaryKWs: ['best dog training tools', 'how to stop dog pulling', 'positive reinforcement dog training', 'dog obedience training'], intent: 'informational', priority: 98, cluster: 'dog-training', week: 1, role: 'cornerstone', internalLinksTarget: 15, linksTo: ['best-no-pull-dog-harness-2026', 'best-dog-training-leash-for-pullers', 'top-dog-training-tools-for-puppies', 'best-anti-bark-training-methods'], difficulty: 'high' },
  // Commercial comparison pages
  { slug: 'best-no-pull-dog-harness-2026', title: 'Best No-Pull Dog Harness (2026) – Tested & Ranked for Pullers', primaryKW: 'best no pull dog harness', secondaryKWs: ['no pull harness', 'front clip harness', 'dog harness for pulling', 'harness for large dog that pulls'], intent: 'commercial', priority: 92, cluster: 'dog-training', week: 1, role: 'hub', internalLinksTarget: 10, linksTo: ['complete-dog-training-guide-2026', 'best-dog-training-leash-for-pullers', 'top-dog-training-tools-for-puppies'], difficulty: 'high' },
  { slug: 'best-dog-training-leash-for-pullers', title: 'Best Dog Training Leash for Pullers (2026) – Tested & Ranked', primaryKW: 'best dog training leash', secondaryKWs: ['leash for pulling dogs', 'anti pull leash', 'dog training leash for pulling'], intent: 'commercial', priority: 85, cluster: 'dog-training', week: 1, role: 'subguide', internalLinksTarget: 8, linksTo: ['complete-dog-training-guide-2026', 'best-no-pull-dog-harness-2026'], difficulty: 'medium' },
  { slug: 'top-dog-training-tools-for-puppies', title: 'Top Dog Training Tools for Puppies (2026) – Start Right', primaryKW: 'puppy training tools', secondaryKWs: ['best tools for puppy training', 'puppy harness', 'puppy training tools for beginners'], intent: 'commercial', priority: 83, cluster: 'dog-training', week: 2, role: 'subguide', internalLinksTarget: 8, linksTo: ['complete-dog-training-guide-2026', 'best-no-pull-dog-harness-2026', 'best-anti-bark-training-methods'], difficulty: 'medium' },
  { slug: 'best-anti-bark-training-methods', title: 'Best Anti-Bark Training Methods (2026) – Humane Solutions That Work', primaryKW: 'anti bark training', secondaryKWs: ['stop dog barking', 'dog bark deterrent', 'best anti bark training solution'], intent: 'commercial', priority: 80, cluster: 'dog-training', week: 2, role: 'subguide', internalLinksTarget: 7, linksTo: ['complete-dog-training-guide-2026', 'best-no-pull-dog-harness-2026'], difficulty: 'medium' },

  // ========== CLUSTER 6: CAT ENRICHMENT (5 guides) ==========
  // Pillar
  { slug: 'best-cat-enrichment-ideas-indoor-cats-2026', title: 'Best Cat Enrichment Ideas for Indoor Cats (2026 Guide)', primaryKW: 'cat enrichment ideas', secondaryKWs: ['indoor cat enrichment', 'best cat enrichment', 'how to keep indoor cats entertained', 'best cat enrichment ideas'], intent: 'informational', priority: 96, cluster: 'cat-enrichment', week: 1, role: 'cornerstone', internalLinksTarget: 12, linksTo: ['best-interactive-cat-toys-that-work', 'best-cat-litter-box-furniture-small-apartments', 'modern-cat-furniture-matches-your-home'], difficulty: 'high' },
  // Commercial comparison pages
  { slug: 'best-interactive-cat-toys-that-work', title: 'Best Interactive Cat Toys That Actually Work (2026) – Tested & Ranked', primaryKW: 'best interactive cat toys', secondaryKWs: ['interactive cat toys for indoor cats', 'cat toys that work', 'best cat toys 2026'], intent: 'commercial', priority: 88, cluster: 'cat-enrichment', week: 1, role: 'hub', internalLinksTarget: 8, linksTo: ['best-cat-enrichment-ideas-indoor-cats-2026', 'best-cat-litter-box-furniture-small-apartments', 'modern-cat-furniture-matches-your-home'], difficulty: 'medium' },
  { slug: 'best-cat-litter-box-furniture-small-apartments', title: 'Best Cat Litter Box Furniture for Small Apartments (2026)', primaryKW: 'cat litter box furniture small apartment', secondaryKWs: ['hidden litter box', 'litter box enclosure', 'cat litter box furniture'], intent: 'commercial', priority: 86, cluster: 'cat-enrichment', week: 2, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-cat-enrichment-ideas-indoor-cats-2026', 'best-interactive-cat-toys-that-work', 'modern-cat-furniture-matches-your-home'], difficulty: 'medium' },
  { slug: 'modern-cat-furniture-matches-your-home', title: 'Modern Cat Furniture That Matches Your Home (2026)', primaryKW: 'modern cat furniture', secondaryKWs: ['stylish cat tree', 'modern cat tree for small space', 'cat furniture that matches home'], intent: 'commercial', priority: 82, cluster: 'cat-enrichment', week: 2, role: 'subguide', internalLinksTarget: 7, linksTo: ['best-cat-enrichment-ideas-indoor-cats-2026', 'best-interactive-cat-toys-that-work', 'best-cat-litter-box-furniture-small-apartments'], difficulty: 'medium' },

  // ========== CLUSTER 7: DOG TRAVEL (6 guides) ==========
  { slug: 'dog-travel-safety-guide', title: 'Dog Travel Safety Guide (2026) – Car Seats, Harnesses & Travel Tips', primaryKW: 'dog travel safety', secondaryKWs: ['dog car seat', 'dog travel harness', 'traveling with a dog', 'pet travel tips'], intent: 'informational', priority: 96, cluster: 'dog-travel', week: 1, role: 'cornerstone', internalLinksTarget: 15, linksTo: ['best-dog-car-seat', 'crash-tested-dog-car-seat-guide', 'dog-travel-safety-laws-by-state', 'safest-dog-car-seat-for-travel'], difficulty: 'high' },
  { slug: 'best-dog-car-seat', title: 'Best Dog Car Seats (2026) – Crash-Tested & Booster Picks', primaryKW: 'best dog car seat', secondaryKWs: ['dog car seat', 'crash tested dog car seat', 'dog booster seat'], intent: 'commercial', priority: 90, cluster: 'dog-travel', week: 1, role: 'hub', internalLinksTarget: 10, linksTo: ['dog-travel-safety-guide', 'crash-tested-dog-car-seat-guide', 'dog-booster-seat-vs-car-hammock'], difficulty: 'high' },
  { slug: 'crash-tested-dog-car-seat-guide', title: 'Crash-Tested Dog Car Seats – What to Look For (2026)', primaryKW: 'crash tested dog car seat', secondaryKWs: ['safest dog car seat', 'CPS tested dog seat'], intent: 'informational', priority: 85, cluster: 'dog-travel', week: 2, role: 'subguide', internalLinksTarget: 7, linksTo: ['dog-travel-safety-guide', 'best-dog-car-seat'], difficulty: 'medium' },
  { slug: 'dog-travel-safety-laws-by-state', title: 'Dog Travel Laws by State – Where Pet Restraint Is Required', primaryKW: 'dog travel laws by state', secondaryKWs: ['pet restraint laws', 'state pet car laws'], intent: 'informational', priority: 78, cluster: 'dog-travel', week: 2, role: 'subguide', internalLinksTarget: 6, linksTo: ['dog-travel-safety-guide', 'best-dog-car-seat'], difficulty: 'low' },
  { slug: 'dog-booster-seat-vs-car-hammock', title: 'Dog Booster Seat vs Car Hammock – Which Is Safer?', primaryKW: 'dog booster seat vs hammock', secondaryKWs: ['dog car hammock', 'dog seat cover vs car seat'], intent: 'comparison', priority: 72, cluster: 'dog-travel', week: 3, role: 'subguide', internalLinksTarget: 5, linksTo: ['dog-travel-safety-guide', 'best-dog-car-seat'], difficulty: 'low' },
  { slug: 'safest-dog-car-seat-for-travel', title: 'Safest Dog Car Seat for Long Road Trips (2026)', primaryKW: 'safest dog car seat for travel', secondaryKWs: ['dog car seat road trip', 'best dog car seat long drive'], intent: 'commercial', priority: 75, cluster: 'dog-travel', week: 3, role: 'subguide', internalLinksTarget: 5, linksTo: ['dog-travel-safety-guide', 'best-dog-car-seat', 'crash-tested-dog-car-seat-guide'], difficulty: 'low' },

  // ========== CLUSTER 8: DOG GROOMING (5 guides) ==========
  { slug: 'dog-grooming-tools-guide', title: 'Dog Grooming Tools Guide (2026) – Brushes, Clippers & Grooming Kits', primaryKW: 'dog grooming tools', secondaryKWs: ['best dog brush', 'dog grooming kit', 'dog nail clippers', 'deshedding tool'], intent: 'informational', priority: 94, cluster: 'dog-grooming', week: 1, role: 'cornerstone', internalLinksTarget: 15, linksTo: ['best-dog-brushes-by-coat-type', 'how-often-groom-dog', 'dog-nail-trimming-guide'], difficulty: 'high' },
  { slug: 'best-dog-brushes-by-coat-type', title: 'Best Dog Brushes by Coat Type (2026) – Slicker, Bristle & Deshedding', primaryKW: 'best dog brush by coat type', secondaryKWs: ['deshedding brush', 'slicker brush for dogs', 'dog brush for shedding'], intent: 'commercial', priority: 88, cluster: 'dog-grooming', week: 1, role: 'hub', internalLinksTarget: 8, linksTo: ['dog-grooming-tools-guide', 'how-often-groom-dog'], difficulty: 'medium' },
  { slug: 'how-often-groom-dog', title: 'How Often Should You Groom Your Dog? – Breed-by-Breed Guide', primaryKW: 'how often to groom a dog', secondaryKWs: ['dog grooming schedule', 'how often to bathe a dog'], intent: 'informational', priority: 80, cluster: 'dog-grooming', week: 2, role: 'subguide', internalLinksTarget: 6, linksTo: ['dog-grooming-tools-guide', 'best-dog-brushes-by-coat-type'], difficulty: 'low' },
  { slug: 'dog-nail-trimming-guide', title: 'How to Trim Dog Nails Safely – Step-by-Step Guide (2026)', primaryKW: 'how to trim dog nails', secondaryKWs: ['dog nail clipping guide', 'cut dog nails at home'], intent: 'informational', priority: 76, cluster: 'dog-grooming', week: 2, role: 'subguide', internalLinksTarget: 5, linksTo: ['dog-grooming-tools-guide'], difficulty: 'low' },
  { slug: 'best-dog-shampoo-guide', title: 'Best Dog Shampoo (2026) – Sensitive, Oatmeal & Medicated Picks', primaryKW: 'best dog shampoo', secondaryKWs: ['dog shampoo for itchy skin', 'oatmeal dog shampoo'], intent: 'commercial', priority: 74, cluster: 'dog-grooming', week: 3, role: 'subguide', internalLinksTarget: 5, linksTo: ['dog-grooming-tools-guide', 'how-often-groom-dog'], difficulty: 'low' },

  // ========== CLUSTER 9: CAT TREES (cornerstone + cluster) ==========
  { slug: 'best-cat-tree-2026', title: 'Best Cat Trees (2026) – 12 Tested Picks for Every Cat Size & Home', primaryKW: 'best cat tree', secondaryKWs: ['cat tree review 2026', 'best cat tree for indoor cats', 'top cat trees'], intent: 'commercial', priority: 97, cluster: 'cat-furniture', week: 1, role: 'cornerstone', internalLinksTarget: 15, linksTo: ['best-cat-trees-small-apartments', 'best-cat-tree-maine-coon', 'best-cat-scratching-post', 'best-floor-to-ceiling-cat-tree', 'best-cat-tree-for-2-cats'], difficulty: 'high' },

  // ========== CLUSTER 10: AUTOMATIC CAT TOYS ==========
  { slug: 'best-automatic-cat-toy-2026', title: 'Best Automatic Cat Toys (2026) – Self-Playing Picks Tested & Ranked', primaryKW: 'best automatic cat toy', secondaryKWs: ['self playing cat toy', 'automatic cat toy review', 'electronic cat toy', 'robotic cat toy'], intent: 'commercial', priority: 94, cluster: 'cat-enrichment', week: 1, role: 'cornerstone', internalLinksTarget: 12, linksTo: ['best-interactive-cat-toys-that-work', 'best-cat-enrichment-ideas-indoor-cats-2026'], difficulty: 'high' },

  // ========== CLUSTER 11: PET CARRIERS & TRAVEL ==========
  { slug: 'best-pet-carrier-for-travel', title: 'Best Pet Carriers for Travel (2026) – Airline Approved & Road Trip Picks', primaryKW: 'best pet carrier for travel', secondaryKWs: ['airline approved pet carrier', 'travel pet carrier', 'cat carrier for travel', 'dog carrier for airplane'], intent: 'commercial', priority: 93, cluster: 'dog-travel', week: 1, role: 'cornerstone', internalLinksTarget: 12, linksTo: ['dog-travel-safety-guide', 'best-dog-car-seat', 'best-cat-carrier-2026', 'best-cat-backpack-carrier'], difficulty: 'high' },
  { slug: 'best-pet-stroller-guide', title: 'Best Pet Strollers (2026) – For Dogs, Cats & Multi-Pet Families', primaryKW: 'best pet stroller', secondaryKWs: ['pet stroller for dogs', 'cat stroller', 'dog stroller for large dogs', 'pet buggy'], intent: 'commercial', priority: 90, cluster: 'dog-travel', week: 2, role: 'hub', internalLinksTarget: 10, linksTo: ['best-pet-carrier-for-travel', 'dog-travel-safety-guide'], difficulty: 'medium' },

  // ========== CLUSTER 12: ORTHOPEDIC DOG BEDS (promoted to cornerstone) ==========
  { slug: 'best-orthopedic-dog-bed-2026', title: 'Best Orthopedic Dog Beds (2026) – Premium Quality Picks for Joint Support', primaryKW: 'best orthopedic dog bed 2026', secondaryKWs: ['orthopedic dog bed review', 'vet recommended dog bed', 'memory foam dog bed 2026'], intent: 'commercial', priority: 96, cluster: 'dog-beds', week: 1, role: 'cornerstone', internalLinksTarget: 15, linksTo: ['best-dog-bed-2026', 'best-orthopedic-dog-bed', 'best-dog-bed-senior-dogs', 'best-dog-bed-for-hip-dysplasia', 'best-dog-bed-large-dogs'], difficulty: 'high' },

  // ========== CLUSTER SUPPORTING GUIDES (new) ==========
  // Cat litter cluster support
  { slug: 'how-to-clean-cat-litter-box', title: 'How to Clean a Cat Litter Box – Step-by-Step Deep Clean Guide', primaryKW: 'how to clean cat litter box', secondaryKWs: ['clean litter box guide', 'sanitize litter box', 'deep clean litter box'], intent: 'informational', priority: 70, cluster: 'cat-litter', week: 5, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026', 'how-often-change-cat-litter', 'best-litter-box-odor-control'], difficulty: 'low' },
  { slug: 'low-tracking-litter-box-guide', title: 'Best Low-Tracking Litter Boxes (2026) – No More Mess', primaryKW: 'low tracking litter box', secondaryKWs: ['litter box less tracking', 'no tracking cat litter', 'best litter box for tracking'], intent: 'commercial', priority: 68, cluster: 'cat-litter', week: 5, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-cat-litter-box-2026', 'how-to-stop-litter-tracking', 'best-top-entry-litter-box'], difficulty: 'low' },
  { slug: 'best-litter-for-odor-control', title: 'Best Cat Litter for Odor Control (2026) – Tested for Real Homes', primaryKW: 'best cat litter for odor control', secondaryKWs: ['odor control cat litter', 'best smelling cat litter', 'litter that controls smell'], intent: 'commercial', priority: 72, cluster: 'cat-litter', week: 6, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-cat-litter-box-2026', 'best-litter-box-odor-control', 'best-litter-box-deodorizer'], difficulty: 'low' },
  { slug: 'automatic-vs-manual-litter-box', title: 'Automatic vs Manual Litter Box – Which Is Worth It? (2026)', primaryKW: 'automatic vs manual litter box', secondaryKWs: ['self cleaning vs manual', 'is automatic litter box worth it'], intent: 'comparison', priority: 65, cluster: 'cat-litter', week: 6, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-self-cleaning-litter-box-2026', 'best-cat-litter-box-2026'], difficulty: 'low' },
  { slug: 'litter-box-for-small-apartment', title: 'Best Litter Box Solutions for Small Apartments (2026)', primaryKW: 'litter box for small apartment', secondaryKWs: ['compact litter box solution', 'apartment litter box ideas'], intent: 'commercial', priority: 66, cluster: 'cat-litter', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-litter-box-for-small-apartment', 'best-cat-litter-box-furniture-enclosures-2026', 'best-cat-litter-box-2026'], difficulty: 'low' },
  // Dog bed cluster support
  { slug: 'orthopedic-dog-bed-benefits', title: 'Orthopedic Dog Bed Benefits – Why Your Dog Needs One', primaryKW: 'orthopedic dog bed benefits', secondaryKWs: ['why orthopedic dog bed', 'benefits of memory foam dog bed', 'does my dog need orthopedic bed'], intent: 'informational', priority: 63, cluster: 'dog-beds', week: 7, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-orthopedic-dog-bed-2026', 'best-orthopedic-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'memory-foam-dog-bed-guide', title: 'Memory Foam Dog Beds – Complete Buying Guide (2026)', primaryKW: 'memory foam dog bed guide', secondaryKWs: ['memory foam dog bed review', 'best memory foam dog bed', 'is memory foam good for dogs'], intent: 'informational', priority: 61, cluster: 'dog-beds', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['best-orthopedic-dog-bed-2026', 'memory-foam-vs-bolster-dog-bed', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'best-dog-bed-for-large-dogs', title: 'Best Dog Beds for Large Dogs (2026) – XL & XXL Picks Tested', primaryKW: 'best dog bed for large dogs', secondaryKWs: ['xl dog bed review', 'big dog bed', 'giant breed dog bed'], intent: 'commercial', priority: 78, cluster: 'dog-beds', week: 4, role: 'subguide', internalLinksTarget: 5, linksTo: ['best-orthopedic-dog-bed-2026', 'best-dog-bed-large-dogs', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'waterproof-dog-bed-guide', title: 'Waterproof Dog Beds – Complete Guide for Puppies & Seniors (2026)', primaryKW: 'waterproof dog bed guide', secondaryKWs: ['waterproof dog bed cover', 'dog bed for incontinence guide'], intent: 'informational', priority: 58, cluster: 'dog-beds', week: 9, role: 'subguide', internalLinksTarget: 3, linksTo: ['best-waterproof-dog-bed', 'best-orthopedic-dog-bed-2026', 'best-dog-bed-2026'], difficulty: 'low' },
  { slug: 'dog-bed-size-chart', title: 'Dog Bed Size Chart – Find the Perfect Fit by Breed & Weight', primaryKW: 'dog bed size chart', secondaryKWs: ['what size dog bed do I need', 'dog bed dimensions by breed'], intent: 'informational', priority: 60, cluster: 'dog-beds', week: 8, role: 'subguide', internalLinksTarget: 4, linksTo: ['dog-bed-size-guide', 'best-dog-bed-2026', 'best-orthopedic-dog-bed-2026'], difficulty: 'low' },
  // Dog leash training support
  { slug: 'best-dog-leash-training-guide', title: 'Best Dog Leash Training Guide (2026) – Stop Pulling in 7 Days', primaryKW: 'dog leash training guide', secondaryKWs: ['how to leash train a dog', 'stop dog pulling on leash', 'leash training tips'], intent: 'informational', priority: 88, cluster: 'dog-training', week: 1, role: 'hub', internalLinksTarget: 10, linksTo: ['complete-dog-training-guide-2026', 'best-no-pull-dog-harness-2026', 'best-dog-training-leash-for-pullers'], difficulty: 'medium' },
];

// ============= WEEKLY SCHEDULE =============

export function getWeeklySchedule(): WeeklySchedule[] {
  const weeks: WeeklySchedule[] = [];
  for (let w = 1; w <= 12; w++) {
    const guides = SCALING_GUIDES.filter(g => g.week === w);
    const clusterCounts = guides.reduce((acc, g) => {
      acc[g.cluster] = (acc[g.cluster] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);
    const focusParts = Object.entries(clusterCounts).map(([c, n]) => `${c}: ${n}`);

    weeks.push({
      week: w,
      label: `Week ${w}${w <= 2 ? ' (14-day pause after)' : ''}`,
      guides,
      focus: focusParts.join(', '),
    });
  }
  return weeks;
}

// ============= CANNIBALIZATION CHECK =============

export function checkCannibalization(): CannibalizationIssue[] {
  const kwMap: Record<string, string[]> = {};
  SCALING_GUIDES.forEach(g => {
    const norm = g.primaryKW.toLowerCase().trim();
    if (!kwMap[norm]) kwMap[norm] = [];
    kwMap[norm].push(g.slug);
  });

  return Object.entries(kwMap)
    .filter(([, slugs]) => slugs.length > 1)
    .map(([keyword, slugs]) => ({
      keyword,
      slugs,
      severity: slugs.length > 2 ? 'high' : 'medium',
    }));
}

// ============= SUMMARY =============

export function getScalingSummary() {
  const total = SCALING_GUIDES.length;
  const byCluster = {
    'cat-litter': SCALING_GUIDES.filter(g => g.cluster === 'cat-litter').length,
    'cat-furniture': SCALING_GUIDES.filter(g => g.cluster === 'cat-furniture').length,
    'dog-beds': SCALING_GUIDES.filter(g => g.cluster === 'dog-beds').length,
    'micro-intent': SCALING_GUIDES.filter(g => g.cluster === 'micro-intent').length,
    'dog-training': SCALING_GUIDES.filter(g => g.cluster === 'dog-training').length,
    'cat-enrichment': SCALING_GUIDES.filter(g => g.cluster === 'cat-enrichment').length,
    'dog-travel': SCALING_GUIDES.filter(g => g.cluster === 'dog-travel').length,
    'dog-grooming': SCALING_GUIDES.filter(g => g.cluster === 'dog-grooming').length,
  };
  const byRole = {
    cornerstone: SCALING_GUIDES.filter(g => g.role === 'cornerstone').length,
    hub: SCALING_GUIDES.filter(g => g.role === 'hub').length,
    subguide: SCALING_GUIDES.filter(g => g.role === 'subguide').length,
  };
  const byDifficulty = {
    low: SCALING_GUIDES.filter(g => g.difficulty === 'low').length,
    medium: SCALING_GUIDES.filter(g => g.difficulty === 'medium').length,
    high: SCALING_GUIDES.filter(g => g.difficulty === 'high').length,
  };
  const cannibalization = checkCannibalization();

  return { total, byCluster, byRole, byDifficulty, cannibalization, weeks: getWeeklySchedule() };
}
