project_id = "nojvgfbcjgipjxpfatmm"

[functions.cj-dropshipping]
verify_jwt = false

[functions.sync-stock]
verify_jwt = false

[functions.generate-seo-text]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false
