// Canonical list of edge functions that MUST be gated by
// `requireInternalOrAdmin` from ./admin-guard.ts.
//
// The auth integration test iterates this list and asserts that each
// deployed function rejects unauthenticated calls with 401 (and rejects
// a wrong `x-internal-secret` header the same way). Add a new entry here
// whenever you protect another function with the shared guard.
export const GUARDED_EDGE_FUNCTIONS = [
  "aec-executive-council",
  "aee-api",
  "agal-auditor",
  "agd-growth-director",
  "ai-ceo-loop",
  "aos-orchestrator",
  "cmdr-orchestrator",
  "ede-api",
  "gad-api",
  "gbd-api",
  "gcd-api",
  "gcp-api",
  "genesis-conversion-intelligence",
  "genesis-first-sale-strike",
  "genesis-golden-customer",
  "gkg-api",
  "gmd-api",
  "gpd-api",
  "gpi-api",
  "growth-intelligence-orchestrator",
  "mil-meta-intelligence",
  "pga-overview-sync",
  "roe-api",
  "spe-api",
  "ailurova-brand-identity",
  "ailurova-compare-at-fix",
  "ailurova-compare-at-forensics",
  "ailurova-custom-storefront-reset",
  "ailurova-delivery-location-fix",
  "ailurova-e2e-live-test",
  "ailurova-fact-matrix-audit",
  "ailurova-final-commerce-polish",
  "ailurova-final-completion",
  "ailurova-final-polish",
  "ailurova-header-logo-swap",
  "ailurova-horizon-rebuild",
  "ailurova-image-hotfix",
  "ailurova-image-render-fix",
  "ailurova-inventory-forensic-audit",
  "ailurova-launch-gate-smoke",
  "ailurova-launch-readiness-audit",
  "ailurova-launch-sprint",
  "ailurova-live-hotfix",
  "ailurova-media-cleanup",
  "ailurova-payments-verify",
  "ailurova-phase2-activate-publish",
  "ailurova-policies-launch",
  "ailurova-policy-pages-fallback",
  "ailurova-premium-storefront",
  "ailurova-price-set",
  "ailurova-privacy-policy-patch",
  "ailurova-processing-time-fix",
  "ailurova-publication-cleanup",
  "ailurova-purchase-controls-repair",
  "ailurova-real-storefront-rebuild",
  "ailurova-scope-audit",
  "ailurova-status-cleanup",
  "ailurova-storefront-finalize",
  "ailurova-storefront-rebuild",
  "ailurova-theme-core-patch",
  "ailurova-theme-inventory",
  "ailurova-theme-rename",
  "ailurova-theme-state",
  "ailurova-us-availability-proof",
  "ailurova-us-pricelist-set",
  "ailurova-us-storefront-verify",
  "ailurova-visual-cleanup",
  "catalog-classify-snapshot",
  "catalog-commerce-proof",
  "catalog-commerce-start",
  "catalog-recovery-batch-execute",
  "catalog-recovery-canary-execute",
  "catalog-recovery-policy-dryrun",
  "catalog-recovery-scan",
  "cj-canary-discovery",
  "cj-existing-location-binding-audit",
  "cj-shopify-connect-scoped",
  "launch-readiness-audit-ailurova",
  "shopify-connection-diagnostics",
  "shopify-introspect-catalog",
  "shopify-inventory-levels-audit",
  "shopify-locations-audit",
  "shopify-scope-verify",
  "shopify-unpublish-25-scoped",
  "shopify-wave2-migrate",
  "shopify-wave3",
  "shopify-wave5",
  "shopify-wave6",
  "shopify-wave7",
  "shopify-wave7-1-forensic",
  "shopify-wave7-2a",
  "us-market-catalog-provision",
  "us-price-launch-configure",
] as const;

export type GuardedEdgeFunction = (typeof GUARDED_EDGE_FUNCTIONS)[number];