
INSERT INTO public.seo_collections (slug, name, primary_keyword, seo_intro, meta_title, meta_description, product_keyword_filter, product_category_filter, secondary_keywords, is_active, display_order)
VALUES
  ('dog-toys', 'Best Dog Toys – Interactive & Durable Picks', 'dog toys', 'Discover our curated collection of the best dog toys for every play style — from interactive puzzle toys and tug ropes to indestructible chew toys for aggressive chewers. Keep your pup entertained, mentally stimulated, and physically active with toys designed for safety and durability. Whether you have a teething puppy or a power-chewing adult, we have toys that last. All products ship from US warehouses with free shipping on orders over $35.', 'Best Dog Toys – Interactive & Durable Picks (2026) | GetPawsy', 'Shop the best dog toys: interactive puzzles, durable chew toys & tug ropes. Keep your pup entertained & active. Free US shipping on $35+.', 'dog toy,chew toy,tug toy,rope toy,interactive dog,puzzle toy,squeaky toy,fetch toy,plush dog toy,ball toy', 'Dog Toys', ARRAY['interactive dog toys','durable dog toys','best chew toys','dog puzzle toys','toys for puppies','indestructible dog toys'], true, 10),

  ('dog-beds', 'Best Dog Beds – Comfortable & Supportive', 'dog beds', 'Find the perfect dog bed for your furry friend — from orthopedic memory foam beds for senior dogs to calming donut beds for anxious pups. Our curated collection features washable covers, waterproof liners, and sizes for every breed from Chihuahua to Great Dane. A quality dog bed supports joint health, improves sleep quality, and gives your dog a safe space to call their own. Free US shipping on orders over $35.', 'Best Dog Beds – Orthopedic & Calming Options (2026) | GetPawsy', 'Shop the best dog beds: orthopedic, memory foam, calming & waterproof options for all breeds. Free US shipping on orders $35+.', 'dog bed,orthopedic dog bed,memory foam dog bed,calming dog bed,elevated dog bed,waterproof dog bed,large dog bed,bolster bed,donut bed', 'Dog Beds', ARRAY['orthopedic dog beds','memory foam dog beds','calming dog beds','waterproof dog beds','large dog beds','elevated dog beds'], true, 11),

  ('dog-harness', 'Best Dog Harnesses – No-Pull & Comfortable', 'dog harness', 'Browse our top-rated dog harnesses designed for comfortable, safe walks — from no-pull front-clip harnesses for dogs that pull to padded adventure harnesses for hiking and travel. A properly fitted harness reduces strain on your dog''s neck, prevents choking, and gives you better control without discomfort. Find crash-tested options for car travel and reflective designs for nighttime visibility. Free shipping on US orders over $35.', 'Best Dog Harnesses – No-Pull & Comfortable Fit (2026) | GetPawsy', 'Shop top-rated dog harnesses: no-pull, padded & reflective options for all breeds. Better control, zero choking. Free US shipping $35+.', 'dog harness,no-pull harness,front clip harness,padded harness,reflective harness,step-in harness,adventure harness,puppy harness,vest harness', 'Dog Harnesses', ARRAY['no-pull dog harness','front clip harness','padded dog harness','reflective dog harness','dog walking harness','best harness for pulling'], true, 12),

  ('cat-toys', 'Best Cat Toys – Interactive & Enriching', 'cat toys', 'Discover the best cat toys to keep your indoor cat entertained and mentally stimulated. From interactive wand toys and laser pointers to self-play puzzle feeders and catnip mice, our collection is curated for cats of all ages. Interactive play reduces boredom, prevents destructive behavior, and strengthens the bond between you and your feline friend. All toys are made with pet-safe materials. Free US shipping on orders over $35.', 'Best Cat Toys for Indoor Cats – Interactive Picks (2026) | GetPawsy', 'Shop the best cat toys: interactive wands, puzzle feeders & catnip toys. Keep indoor cats happy & stimulated. Free US shipping $35+.', 'cat toy,interactive cat toy,wand toy,laser toy,catnip toy,cat puzzle,feather toy,mouse toy,cat ball,cat enrichment', 'Cat Toys', ARRAY['interactive cat toys','best cat toys indoor','catnip toys','cat puzzle feeders','wand toys for cats','cat enrichment toys'], true, 20),

  ('cat-litter-boxes', 'Best Cat Litter Boxes – Self-Cleaning & Odor-Free', 'cat litter boxes', 'Find the perfect litter box for your cat — from automatic self-cleaning models to covered and top-entry designs that control odor and keep litter contained. Our curated collection includes solutions for multi-cat households, large cats, and small apartments. A quality litter box with proper maintenance is essential for your cat''s hygiene and your home''s freshness. Free US shipping on orders over $35.', 'Best Cat Litter Boxes – Self-Cleaning & Odor Control (2026) | GetPawsy', 'Shop top cat litter boxes: self-cleaning, covered & odor-control models. Perfect for multi-cat homes. Free US shipping on $35+.', 'litter box,self cleaning litter,automatic litter,covered litter box,top entry litter,litter enclosure,odor control litter,large litter box,cat litter', 'Cat Litter Boxes', ARRAY['self-cleaning litter box','automatic litter box','best litter box odor control','covered litter box','top entry litter box','litter box furniture'], true, 21),

  ('cat-scratching-posts', 'Best Cat Scratching Posts – Durable & Stylish', 'cat scratching posts', 'Protect your furniture with our curated collection of cat scratching posts — from tall sisal-wrapped towers to modern cardboard scratchers and wall-mounted options. Scratching is a natural behavior that keeps claws healthy, stretches muscles, and relieves stress. Choose from posts, pads, and loungers that match your home décor while satisfying your cat''s instincts. Free shipping on US orders over $35.', 'Best Cat Scratching Posts – Sisal & Modern Designs (2026) | GetPawsy', 'Shop durable cat scratching posts: sisal, cardboard & wall-mounted designs. Save your furniture. Free US shipping on orders $35+.', 'scratching post,cat scratcher,sisal post,cardboard scratcher,wall scratcher,scratch pad,cat scratch,scratching board,scratch lounge', 'Cat Scratching Posts', ARRAY['sisal scratching post','cat scratcher cardboard','wall mounted scratcher','tall scratching post','modern cat scratcher','best scratching post'], true, 22),

  ('automatic-cat-feeders', 'Best Automatic Cat Feeders – Smart & Timed', 'automatic cat feeders', 'Keep your cat on a healthy feeding schedule with our curated selection of automatic cat feeders — from programmable timed dispensers to smart WiFi-enabled feeders with portion control. Ideal for busy pet parents, multi-cat households, and cats that need weight management. Automatic feeders prevent overeating, ensure consistent meal times, and give you peace of mind when you''re away. Free US shipping on orders over $35.', 'Best Automatic Cat Feeders – Smart Timed Dispensers (2026) | GetPawsy', 'Shop automatic cat feeders: timed, WiFi-enabled & portion-controlled. Perfect for busy pet parents. Free US shipping on $35+.', 'automatic feeder,cat feeder,timed feeder,smart feeder,cat food dispenser,wifi feeder,portion control feeder,programmable feeder,auto feeder', 'Cat Feeders', ARRAY['automatic cat feeder','timed cat feeder','smart cat feeder','wifi pet feeder','cat food dispenser','portion control feeder'], true, 23),

  ('pet-grooming-tools', 'Best Pet Grooming Tools – Brushes, Clippers & More', 'pet grooming tools', 'Groom your pets like a pro with our curated collection of grooming tools — from deshedding brushes and nail clippers to grooming gloves and ear cleaning kits. Regular grooming reduces shedding, prevents matting, improves skin health, and strengthens the bond with your pet. Our tools work for both dogs and cats of all coat types. Free shipping on US orders over $35.', 'Best Pet Grooming Tools – Brushes & Clippers (2026) | GetPawsy', 'Shop pet grooming tools: deshedding brushes, nail clippers & grooming kits for dogs and cats. Free US shipping on orders $35+.', 'grooming,brush,deshedding,nail clipper,grooming glove,comb,trimmer,grooming kit,pet brush,fur remover,undercoat rake', 'Pet Grooming', ARRAY['deshedding brush','pet nail clippers','grooming glove','undercoat rake','pet grooming kit','dog brush','cat brush'], true, 30)

ON CONFLICT (slug) DO NOTHING;
