INSERT INTO public.pcie_v2_scene_generators (slug, name, prompt_fragment, enabled, metadata) VALUES
  ('luxury_home','Luxury Home','luxury home interior, marble, brass accents, designer furniture',true,'{"world_family":"interior"}'::jsonb),
  ('minimal_interior','Minimal Interior','minimal scandinavian interior, neutral palette, clean lines',true,'{"world_family":"interior"}'::jsonb),
  ('farmhouse','Farmhouse','modern farmhouse, shiplap, warm wood, cozy textures',true,'{"world_family":"interior"}'::jsonb),
  ('modern_apartment','Modern Apartment','modern city apartment, large windows, soft daylight',true,'{"world_family":"interior"}'::jsonb),
  ('tiny_apartment','Tiny Apartment','small apartment, compact layout, smart storage',true,'{"world_family":"interior"}'::jsonb),
  ('camping','Camping','tent camping, forest, golden hour, campfire warmth',true,'{"world_family":"outdoor"}'::jsonb),
  ('rv_life','RV Life','RV interior on a scenic road trip, mountain backdrop',true,'{"world_family":"outdoor"}'::jsonb),
  ('beach','Beach','sandy beach, ocean breeze, warm light',true,'{"world_family":"outdoor"}'::jsonb),
  ('outdoor_adventure','Outdoor Adventure','hiking trail, rugged outdoor scene',true,'{"world_family":"outdoor"}'::jsonb),
  ('dog_park','Dog Park','sunny suburban dog park with green grass',true,'{"world_family":"outdoor"}'::jsonb),
  ('cat_cafe','Cat Cafe','cozy cat cafe, plants, soft lighting',true,'{"world_family":"lifestyle"}'::jsonb),
  ('travel','Travel','travel lifestyle, suitcase, destination vibe',true,'{"world_family":"lifestyle"}'::jsonb),
  ('airport','Airport','modern airport terminal, large windows',true,'{"world_family":"lifestyle"}'::jsonb),
  ('vacation','Vacation','vacation rental, relaxed beachside or mountain stay',true,'{"world_family":"lifestyle"}'::jsonb),
  ('pet_hotel','Pet Hotel','upscale pet hotel suite, branded amenities',true,'{"world_family":"lifestyle"}'::jsonb),
  ('groomer','Professional Groomer','professional grooming salon, clean white tile',true,'{"world_family":"professional"}'::jsonb),
  ('veterinarian','Veterinarian','veterinary clinic exam room, modern equipment',true,'{"world_family":"professional"}'::jsonb),
  ('dog_trainer','Dog Trainer','training facility, agility props',true,'{"world_family":"professional"}'::jsonb),
  ('senior_dog','Senior Dogs','older dog resting on orthopedic bed, soft window light',true,'{"world_family":"audience"}'::jsonb),
  ('senior_cat','Senior Cats','elderly cat in a sunlit window perch',true,'{"world_family":"audience"}'::jsonb),
  ('puppy','Puppies','energetic puppy, playful scene',true,'{"world_family":"audience"}'::jsonb),
  ('kitten','Kittens','tiny kitten, curious expression',true,'{"world_family":"audience"}'::jsonb),
  ('golden_retriever','Golden Retriever','happy golden retriever, family setting',true,'{"world_family":"breed"}'::jsonb),
  ('french_bulldog','French Bulldog','french bulldog in chic apartment',true,'{"world_family":"breed"}'::jsonb),
  ('german_shepherd','German Shepherd','german shepherd outdoor portrait',true,'{"world_family":"breed"}'::jsonb),
  ('labrador','Labrador','labrador in lake or backyard scene',true,'{"world_family":"breed"}'::jsonb),
  ('cat_mom','Cat Mom','cat mom lifestyle, woman with multiple cats',true,'{"world_family":"persona"}'::jsonb),
  ('dog_mom','Dog Mom','dog mom lifestyle, casual outdoor weekend',true,'{"world_family":"persona"}'::jsonb),
  ('family','Family','family with pets, warm at-home scene',true,'{"world_family":"persona"}'::jsonb),
  ('busy_pro','Busy Professional','busy professional managing pet between meetings',true,'{"world_family":"persona"}'::jsonb),
  ('funny_pet','Funny Pets','candid funny pet moment, slight chaos',true,'{"world_family":"emotional"}'::jsonb),
  ('emotional_story','Emotional Storytelling','intimate bond moment between owner and pet',true,'{"world_family":"emotional"}'::jsonb),
  ('problem_solution','Problem / Solution','split before/after problem-solution layout',true,'{"world_family":"format"}'::jsonb),
  ('educational','Educational','educational diagram-style scene, neutral backdrop',true,'{"world_family":"format"}'::jsonb),
  ('infographic','Infographic','infographic style with iconography on white',true,'{"world_family":"format"}'::jsonb),
  ('top5_tips','Top 5 Tips','top 5 tips list layout, numbered cards',true,'{"world_family":"format"}'::jsonb),
  ('checklist','Checklist','checklist layout, checked boxes',true,'{"world_family":"format"}'::jsonb),
  ('buying_guide','Buying Guide','buying guide product comparison layout',true,'{"world_family":"format"}'::jsonb),
  ('comparison','Comparison','side-by-side comparison layout',true,'{"world_family":"format"}'::jsonb),
  ('amazon_review','Amazon Review Style','authentic review photo, kitchen counter or living room',true,'{"world_family":"format"}'::jsonb),
  ('ugc_iphone','UGC iPhone','candid iPhone shot, slightly imperfect framing',true,'{"world_family":"capture"}'::jsonb),
  ('pov','POV','first-person POV, leash or hand in frame',true,'{"world_family":"capture"}'::jsonb),
  ('closeup_product','Close-up Product','close-up product detail, shallow depth of field',true,'{"world_family":"capture"}'::jsonb),
  ('studio_photography','Studio Photography','clean studio backdrop, soft key light',true,'{"world_family":"capture"}'::jsonb),
  ('macro_detail','Macro Detail','macro detail of fabric, fur, or texture',true,'{"world_family":"capture"}'::jsonb),
  ('before_after','Before / After','before/after split frame transformation',true,'{"world_family":"format"}'::jsonb),
  ('holiday','Holiday','generic holiday decor, warm string lights',true,'{"world_family":"seasonal"}'::jsonb),
  ('summer','Summer','bright summer scene, beach or backyard',true,'{"world_family":"seasonal"}'::jsonb),
  ('fourth_of_july','Fourth of July','fourth of july americana decor',true,'{"world_family":"seasonal"}'::jsonb),
  ('weekend_cleaning','Weekend Cleaning','weekend cleaning routine, sunny morning',true,'{"world_family":"seasonal"}'::jsonb),
  ('back_to_school','Back to School','back to school morning routine',true,'{"world_family":"seasonal"}'::jsonb),
  ('christmas','Christmas','christmas tree, warm holiday lights',true,'{"world_family":"seasonal"}'::jsonb),
  ('halloween','Halloween','halloween decor, pumpkins, cozy spooky vibe',true,'{"world_family":"seasonal"}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET enabled = EXCLUDED.enabled, metadata = EXCLUDED.metadata, prompt_fragment = EXCLUDED.prompt_fragment;