
UPDATE public.pinterest_pin_queue SET
  category_key = v.ck,
  overlay_text = v.ov,
  pin_title = v.title,
  pin_description = v.pdesc,
  status = 'queued',
  approved_at = now(),
  priority = 'high',
  publish_attempts = 0,
  publishing_started_at = NULL,
  scheduled_at = now(),
  rejection_reason = NULL,
  error_message = NULL,
  last_publish_error = NULL,
  qa_reasons = '{}',
  updated_at = now()
FROM (VALUES
  ('0e0ff754-3a0a-4abf-9485-51378104fa3f'::uuid, 'cat-trees', 'Sturdy scratching post',
    'Water Hyacinth Cat Tree with Sisal Posts',
    'Handwoven 41-inch water hyacinth cat tree with three sisal scratching posts — a stable indoor climbing tower for cats.'),
  ('272b84f9-2b4a-4a33-b8c6-c9719f0b944a'::uuid, 'cat-trees', 'Multi-level cat playground',
    'Dark Gray 2-Tier Cat Tree Tower',
    '33.5-inch dark gray 2-tier cat tree tower with sisal scratching posts — a compact multi-level cat playground.'),
  ('3e56eb56-f955-43a9-849e-b65f0e0c2378'::uuid, 'cat-trees', 'Multi-level cat playground',
    'Wall-Mounted 4-Layer Cat Tree',
    'PawHut wall-mounted 4-layer cat tree with cushions and scratching posts — a space-saving indoor climbing playground for cats.'),
  ('418810af-0d0f-45ba-837f-f9bcea123ecc'::uuid, 'cat-litter', 'Less mess',
    'Hooded Enclosed Cat Litter Box',
    'Hooded enclosed cat litter box with a litter-catching mat — a cleaner litter routine with less mess.'),
  ('b6845027-6e7b-49bc-ad85-3ca28d15834f'::uuid, 'cat-trees', 'Cat tree that stays put',
    'Floor-to-Ceiling 4-Tier Cat Tree',
    '85.5-inch height-adjustable floor-to-ceiling 4-tier cat tree — a stable climbing tower that stays put.'),
  ('b84af2cb-8b84-4ec7-92db-9eb3c6adab22'::uuid, 'default', 'Made for everyday pet life',
    'Cat Puzzle Toy with Spring Wand',
    'Interactive cat puzzle toy with treat-dispensing ball and spring-loaded wand — enrichment made for everyday indoor cats.'),
  ('c67b4f77-37e1-4280-9db9-8048ab483ce5'::uuid, 'cat-litter', 'Easy cleaning',
    'Double-Layer Rice Cat Litter Mat',
    'Double-layer rice cat litter mat — traps loose litter and cleans up easily for less mess around the box.'),
  ('f17b5e91-5da9-4578-9f94-3180e6fc83d5'::uuid, 'default', 'Made for everyday pet life',
    'Interactive Cat Entertainment Set',
    'Interactive cat entertainment set with rotating disk, feather teasers, tumbler and windmill toy — indoor play made for everyday routines.')
) AS v(vid, ck, ov, title, pdesc)
WHERE pinterest_pin_queue.id = v.vid;
