INSERT INTO public.pcie_v2_scene_generators (slug, name, prompt_fragment, weight, enabled, applies_to, metadata) VALUES
('luxury_apartment','Luxury Apartment','upscale Manhattan high-rise apartment with floor-to-ceiling windows, marble accents, designer furniture, city skyline view',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('texas_ranch','Texas Ranch','sprawling Texas ranch porch at dusk, wood beams, leather chairs, golden plains in background',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('beach_house','Beach House','airy Cape Cod beach house with whitewashed wood floors, linen drapes, ocean breeze through open doors',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('mountain_cabin','Mountain Cabin','cozy Colorado log cabin with stone fireplace, plaid throws, snow falling outside picture window',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('rv_adventure','RV Adventure','modern Airstream RV interior parked by a desert canyon at golden hour',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('camping_weekend','Camping Weekend','camping tent at a forest clearing, lantern light, sleeping bags, marshmallow campfire ambience',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('national_park','National Park','Yosemite valley trail with morning mist, granite cliffs in distance, golden California sun',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('family_picnic','Family Picnic','red gingham blanket on green grass, picnic basket, sunny afternoon at a city park',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('coffee_shop','Coffee Shop','independent Brooklyn coffee shop window seat, espresso steam, soft jazz light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('pet_friendly_hotel','Pet Friendly Hotel','boutique pet friendly hotel suite with white linens, welcome treat basket, soft morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('road_trip','Road Trip','Pacific Coast Highway road trip stop, vintage SUV trunk open, ocean cliffs in background',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('backyard_bbq','Backyard BBQ','suburban backyard summer BBQ at golden hour, string lights, grill smoke, friends gathered',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('autumn_forest','Autumn Forest','New England autumn forest path with golden and crimson leaves carpet, soft hazy sunlight',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('winter_cabin','Winter Cabin','Vermont winter cabin with snow on the roof, warm window glow, fresh snowfall at dusk',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('christmas_morning','Christmas Morning','Christmas morning living room with decorated tree, wrapped gifts, fireplace, soft snow outside',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('rainy_sunday','Rainy Sunday','cozy Sunday morning with rain on the window, knit blanket, mug of coffee, soft grey light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('home_office','Home Office','modern work-from-home office with bookshelf wall, ergonomic chair, natural window light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('college_dorm','College Dorm','compact college dorm room with string lights, tapestry wall, twin bed, study desk with laptop',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('luxury_penthouse','Luxury Penthouse','Manhattan penthouse terrace at blue hour, infinity skyline, modern minimalist interior',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('industrial_loft','Industrial Loft','Brooklyn industrial loft with exposed brick, steel windows, concrete floor, vintage leather sofa',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('modern_farmhouse','Modern Farmhouse','modern white farmhouse kitchen with shiplap, black hardware, oak island, barn door',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('urban_city','Urban City','sidewalk cafe in downtown Chicago, city street life, late afternoon golden light between buildings',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('lake_house','Lake House','Lake Tahoe dock at sunrise, wooden lake house, paddleboard on the calm water',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('garden_oasis','Garden Oasis','lush backyard garden with stone path, hydrangeas, wrought iron bench, dappled afternoon light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('pet_cafe','Pet Cafe','trendy pet-friendly cafe with concrete bar, pastel walls, latte art and a dog bowl on the floor',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('vet_clinic','Vet Clinic','calm modern veterinary clinic exam room with light wood, soft greens, friendly atmosphere',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('pet_boutique','Pet Boutique','upscale pet boutique with marble counter, pastel collars, brass shelving, gold accents',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('childrens_bedroom','Children''s Bedroom','whimsical kids bedroom with twin beds, soft rug, fairy lights, plush toys, pastel pink walls',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('playroom','Playroom','sunlit playroom with wooden toys, soft mat, low bookshelf, oversized teddy in the corner',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('dog_beach','Dog Beach','wide sandy dog beach at sunset, gentle waves, footprints in sand, warm orange sky',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('cat_sanctuary','Cat Sanctuary','sunny cat sanctuary room with tall window perches, climbing shelves, woven baskets',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('senior_living','Senior Living','warm grandparent''s living room with floral sofa, framed photos, afternoon tea on the side table',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('luxury_resort','Luxury Resort','tropical luxury resort cabana with infinity pool, palm shadows, crisp white linens',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('sailboat','Sailboat','sailboat deck at sea, teak floors, white sails, blue ocean horizon, midday sun',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('harbor','Harbor','New England harbor at sunrise, wooden pier, fishing boats, soft golden mist',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('yacht','Yacht','sleek modern yacht deck at golden hour, Mediterranean blue water, white cushions',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('snow_adventure','Snow Adventure','fresh powder mountain trail with snowshoes, pine trees dusted in snow, bluebird sky',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('summer_vacation','Summer Vacation','beach umbrella and woven tote on white sand, turquoise water, hot summer afternoon',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('scandi_loft','Scandi Loft','Scandinavian loft with light oak floor, white walls, single statement chair, large arched window',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('japandi_studio','Japandi Studio','Japandi studio with low platform bed, paper lantern, bamboo, neutral muted palette',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('mid_century_living','Mid Century Living','mid-century modern living room with walnut credenza, mustard armchair, sunburst mirror',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('boho_bedroom','Boho Bedroom','boho bedroom with macrame wall hanging, layered rugs, plants, sheer curtain morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('coastal_cottage','Coastal Cottage','Nantucket coastal cottage with blue and white stripes, weathered shiplap, hydrangeas in vase',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('desert_villa','Desert Villa','Palm Springs desert villa with terracotta floors, cactus garden, modernist lines, golden sun',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('ski_chalet','Ski Chalet','Aspen ski chalet with stone fireplace, fur throws, hot cocoa on a wooden tray, snowy view',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('alpine_lodge','Alpine Lodge','alpine lodge great room with antler chandelier, vaulted timber ceiling, mountain view window',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('treehouse','Treehouse','modern treehouse cabin with round window, suspended bridge view, forest canopy at golden hour',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('lakefront_dock','Lakefront Dock','wooden lake dock at sunrise, two Adirondack chairs, calm reflective water',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('cabin_porch','Cabin Porch','wraparound cabin porch at dusk, rocking chairs, lantern light, fireflies in the field',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('screened_porch','Screened Porch','Southern screened porch with wicker furniture, ceiling fan, sweet tea, summer evening',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('sunroom','Sunroom','bright sunroom filled with potted plants, rattan chair, tile floor, late morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('reading_nook','Reading Nook','cozy bay window reading nook with cushions, stacked books, soft afternoon light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('mudroom','Mudroom','modern farmhouse mudroom with bench, hooks, boots, leash hung neatly by the door',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('laundry_room','Laundry Room','bright laundry room with folded linens, marble counter, woven basket, sunlight from window',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('walk_in_closet','Walk In Closet','luxury walk-in closet with island, soft lighting, organized shelves, plush ottoman',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('art_studio','Art Studio','painter''s loft studio with canvases, north-facing window, paint-splattered wood floor',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('music_room','Music Room','music room with upright piano, framed records, persian rug, warm lamp light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('library_room','Library Room','floor-to-ceiling library with rolling ladder, leather club chair, fireplace, afternoon light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('basement_den','Basement Den','finished basement den with sectional, plaid throw, billiard table, warm pendant lights',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('attic_loft','Attic Loft','attic loft bedroom with skylights, exposed beams, white linens, morning sun streaming in',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('rooftop_terrace','Rooftop Terrace','Brooklyn rooftop terrace at golden hour, string lights, lounge chairs, Manhattan skyline view',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('pool_deck','Pool Deck','modernist pool deck at midday, turquoise water, white loungers, palm shadows',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('garden_patio','Garden Patio','brick garden patio with bistro table, climbing roses, evening candlelight',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('vegetable_garden','Vegetable Garden','raised-bed vegetable garden in summer, ripe tomatoes, herbs, watering can in soft sun',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('greenhouse','Greenhouse','Victorian glass greenhouse interior with potted plants, wooden bench, dappled light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('herb_garden','Herb Garden','kitchen herb garden in terracotta pots on a windowsill, sunlight on basil and rosemary',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('koi_pond','Koi Pond','Japanese koi pond garden with stone lantern, footbridge, mossy stones, soft morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('fire_pit_evening','Fire Pit Evening','backyard fire pit at twilight, Adirondack chairs, marshmallow sticks, glowing embers',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('hammock_yard','Hammock Yard','backyard hammock between two oaks, dappled afternoon light, lemonade on side table',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('picnic_blanket_park','Picnic Blanket Park','plaid picnic blanket in a sunlit park, wicker basket, frisbee, summer afternoon',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('dog_friendly_brewery','Dog Friendly Brewery','outdoor brewery patio at sunset, picnic tables, string lights, fall harvest mood',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('farmers_market','Farmers Market','Saturday farmers market with crates of produce, flowers, canvas tote, golden morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('antique_store','Antique Store','cluttered charming antique store aisle with vintage finds, brass lamps, warm tungsten glow',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('bookstore_cafe','Bookstore Cafe','independent bookstore cafe with stacked books, leather armchair, cappuccino on side table',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('art_gallery','Art Gallery','minimalist gallery with white walls, polished concrete floor, single dramatic spotlight',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('yoga_studio','Yoga Studio','sunlit yoga studio with bamboo floor, rolled mats, plant in the corner, soft morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('gym_morning','Gym Morning','modern home gym with rubber floor, kettlebells, mirror wall, fresh morning sweat session',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('hiking_trail','Hiking Trail','Pacific Northwest hiking trail through ferns, mossy trees, soft filtered green light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('mountain_summit','Mountain Summit','mountain summit at sunrise with panoramic valley view, cool blue light, alpenglow on peaks',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('redwood_forest','Redwood Forest','California redwood forest with towering trunks, sun shafts through canopy, mossy floor',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('pacific_coast','Pacific Coast','Big Sur cliffs above the Pacific, winding highway, golden hour mist',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('desert_canyon','Desert Canyon','Utah desert canyon at golden hour, red rock walls, lone juniper tree, warm shadows',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('joshua_tree','Joshua Tree','Joshua Tree desert at sunset, silhouetted trees, purple-pink sky, warm dry breeze',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('rocky_mountain','Rocky Mountain','Colorado Rocky Mountain alpine lake with reflected peaks, wildflowers in foreground',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('smoky_mountains','Smoky Mountains','Great Smoky Mountains overlook at dawn, layered blue ridges, soft mist between peaks',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('cape_cod','Cape Cod','Cape Cod dune path with sea grass, weathered fence, foggy beach in the distance',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('key_west','Key West','Key West conch cottage porch with palms, pastel shutters, bright Caribbean sun',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('charleston_porch','Charleston Porch','Charleston single house piazza with ceiling fans, ferns, joggling board, soft Southern light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('savannah_garden','Savannah Garden','Savannah courtyard garden with moss-draped oak, iron gate, brick path, dappled light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('napa_vineyard','Napa Vineyard','Napa Valley vineyard rows at sunset, warm golden hills, wine glass on terrace railing',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('sonoma_winery','Sonoma Winery','Sonoma rustic winery patio, oak barrels, picnic table, warm afternoon under string lights',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('oregon_coast','Oregon Coast','Oregon coast sea stacks at sunset, dramatic surf, driftwood beach, moody sky',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('alaska_lodge','Alaska Lodge','Alaska wilderness lodge with timber walls, antler decor, mountain river view',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('montana_ranch','Montana Ranch','Montana ranch big-sky pasture at golden hour, wood barn, grazing horses in distance',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('new_england_fall','New England Fall','New England town in peak fall foliage, white church steeple, red and orange trees',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('vermont_cabin','Vermont Cabin','Vermont maple-syrup cabin in early autumn, smoke from chimney, fiery red maple leaves',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('midwest_farm','Midwest Farm','Iowa farmhouse front porch, white siding, cornfield horizon, golden afternoon',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('brooklyn_brownstone','Brooklyn Brownstone','Brooklyn brownstone stoop in spring, flower planters, tree-lined street, soft morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('miami_balcony','Miami Balcony','Miami high-rise balcony at sunset, palm tree silhouettes, ocean view, art deco lines',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('austin_bungalow','Austin Bungalow','Austin craftsman bungalow porch with string lights, fiddle leaf fig, warm Texas evening',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('denver_loft','Denver Loft','Denver industrial loft with mountain view, exposed ductwork, leather sofa, blue hour',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('portland_craftsman','Portland Craftsman','Portland craftsman home library with built-ins, rain on the window, warm lamp light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('seattle_houseboat','Seattle Houseboat','Seattle Lake Union houseboat deck with kayak, evergreens, soft overcast morning',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('palm_springs_modern','Palm Springs Modern','mid-century Palm Springs home with breeze blocks, pool, cactus, sharp desert sun',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('hampton_beach_house','Hampton Beach House','Hamptons shingle-style beach house with hydrangeas, white porch, dune grass',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('hawaiian_lanai','Hawaiian Lanai','Hawaiian lanai with rattan furniture, tropical plants, ocean breeze, golden afternoon',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('alaska_winter','Alaska Winter','Alaska winter cabin with northern lights overhead, snow drifts, glowing windows',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('fall_pumpkin_patch','Fall Pumpkin Patch','fall pumpkin patch with hay bales, orange pumpkins, golden afternoon, families wandering',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('valentines_morning','Valentines Morning','Valentine''s morning kitchen with heart pancakes, fresh roses, soft pink window light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('easter_brunch','Easter Brunch','Easter brunch tablescape with pastel eggs, tulips, linen napkins, sunny spring light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('mothers_day_breakfast','Mothers Day Breakfast','Mother''s Day breakfast tray with flowers, coffee, handwritten card, soft morning light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('fathers_day_grill','Fathers Day Grill','Father''s Day backyard grill, smoking ribs, ice-cold drinks, summer evening',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('thanksgiving_table','Thanksgiving Table','Thanksgiving dinner table with turkey, candles, fall florals, warm family gathering glow',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('new_years_eve','New Years Eve','New Year''s Eve apartment celebration with confetti, champagne flutes, city lights',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('snow_day_indoors','Snow Day Indoors','snow day indoors with hot cocoa, knit blanket, board games, window full of falling snow',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('first_snowfall','First Snowfall','first snowfall morning, footprints in fresh powder, hushed neighborhood, soft blue light',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('foggy_morning','Foggy Morning','foggy morning porch with steaming coffee mug, muted landscape, atmospheric silence',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('midnight_kitchen','Midnight Kitchen','midnight kitchen scene with single pendant on, glass of water, calm quiet darkness',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('dawn_kitchen','Dawn Kitchen','dawn kitchen with first light through window, coffee dripping, peaceful start of the day',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4')),
('stormy_evening','Stormy Evening','stormy evening living room with rain lashing windows, lamp on, blanket and book',1.0,true,'[]'::jsonb,jsonb_build_object('category','world','source','genesis_v4'))
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.pcie_v2_camera_presets (slug, name, prompt_fragment, weight, enabled) VALUES
('fisheye_action','Fisheye Action','fisheye lens, wide curved perspective, action-packed framing',1.0,true),
('drone_overhead','Drone Overhead','drone overhead top-down shot, geometric composition, altitude perspective',1.0,true),
('drone_orbit','Drone Orbit','cinematic drone orbit, sweeping rotation around subject',1.0,true),
('gopro_chest','GoPro Chest','GoPro chest-mount POV, immersive first-person motion',1.0,true),
('gopro_floor','GoPro Floor','GoPro ground-level wide shot, dynamic low perspective',1.0,true),
('iphone_handheld','iPhone Handheld','iPhone handheld vertical, natural authentic UGC feel',1.0,true),
('iphone_selfie','iPhone Selfie','iPhone selfie angle, intimate over-the-shoulder candid',1.0,true),
('vertical_smartphone','Vertical Smartphone','vertical smartphone framing, 9:16 candid composition',1.0,true),
('magazine_editorial','Magazine Editorial','editorial magazine spread, refined art direction, ample negative space',1.0,true),
('magazine_cover','Magazine Cover','glossy magazine cover composition, bold subject, clean background',1.0,true),
('commercial_studio','Commercial Studio','commercial studio lighting, polished product hero look',1.0,true),
('commercial_lifestyle','Commercial Lifestyle','commercial lifestyle shoot, aspirational yet natural',1.0,true),
('documentary_natural','Documentary Natural','documentary natural light photojournalism style',1.0,true),
('documentary_candid','Documentary Candid','candid documentary unposed moment, authentic emotion',1.0,true),
('tracking_lateral','Tracking Lateral','lateral tracking shot, smooth sideways motion, cinematic',1.0,true),
('tracking_follow','Tracking Follow','follow tracking shot from behind, sense of journey',1.0,true),
('pet_eye_level','Pet Eye Level','camera at pet eye level, immersive low perspective',1.0,true),
('pet_paw_level','Pet Paw Level','camera at paw level, ground-up dramatic perspective',1.0,true),
('owner_pov','Owner POV','owner first-person POV, looking down at pet',1.0,true),
('owner_over_shoulder','Owner Over Shoulder','over-the-shoulder of owner looking at pet, intimate angle',1.0,true),
('action_burst','Action Burst','frozen action burst frame, motion captured mid-leap',1.0,true),
('slow_motion_freeze','Slow Motion Freeze','slow-motion freeze frame, hair and ears mid-air',1.0,true),
('silhouette_window','Silhouette Window','silhouette against bright window, graphic contrast',1.0,true),
('backlit_golden','Backlit Golden','backlit golden hour, glowing rim light, warm haze',1.0,true),
('rim_light_evening','Rim Light Evening','rim light evening shot, subject edge-lit against shadow',1.0,true),
('window_light_soft','Window Light Soft','soft side window light, gentle wraparound shadow',1.0,true),
('north_light_studio','North Light Studio','north-facing window studio light, painterly and even',1.0,true),
('kitchen_window_morning','Kitchen Window Morning','kitchen window morning light, warm domestic mood',1.0,true),
('golden_hour_porch','Golden Hour Porch','golden hour porch light, long warm shadows',1.0,true),
('blue_hour_balcony_cam','Blue Hour Balcony','blue hour balcony shot, cool ambient with warm interior glow',1.0,true),
('harsh_noon_outdoor','Harsh Noon Outdoor','harsh noon sun outdoor, crisp shadows, summer vibrancy',1.0,true),
('overcast_diffused','Overcast Diffused','overcast soft diffused light, even tonal range',1.0,true),
('candle_warm_low','Candle Warm Low','candlelit warm low light, intimate evening tone',1.0,true),
('fireplace_glow','Fireplace Glow','fireplace glow, flickering warm cast on subject',1.0,true),
('lamp_pool_warm','Lamp Pool','warm lamp pool of light, surrounding shadow, cinematic',1.0,true),
('night_ambient','Night Ambient','night ambient with practical lights, moody and cinematic',1.0,true),
('before_after_split','Before After Split','before/after side-by-side composition, clear narrative',1.0,true),
('lifestyle_wide','Lifestyle Wide','wide lifestyle environmental shot, room as hero',1.0,true),
('lifestyle_mid','Lifestyle Mid','mid lifestyle shot, subject and context balanced',1.0,true),
('ultra_close_macro','Ultra Close Macro','ultra-close macro detail, texture-driven storytelling',1.0,true),
('environmental_portrait','Environmental Portrait','environmental portrait, subject in their context',1.0,true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.pcie_v2_emotions (slug, name, prompt_fragment, weight, enabled) VALUES
('nostalgia','Nostalgia','warm nostalgic memory-like mood',1.0,true),
('awe','Awe','awe and wonder at scale or beauty',1.0,true),
('gratitude','Gratitude','grateful and appreciative tone',1.0,true),
('mischief','Mischief','playful mischievous energy',1.0,true),
('serenity','Serenity','serene calm peacefulness',1.0,true),
('pride','Pride','proud accomplished feeling',1.0,true),
('hopeful','Hopeful','hopeful optimistic forward-looking',1.0,true),
('anticipation','Anticipation','anticipation and excitement for what comes next',1.0,true),
('snug_coziness','Snug Coziness','snug coziness, hygge warmth',1.0,true),
('achievement','Achievement','achievement and satisfaction',1.0,true),
('freedom','Freedom','freedom and open possibility',1.0,true),
('belonging','Belonging','sense of belonging and home',1.0,true),
('wonder','Wonder','childlike wonder and discovery',1.0,true),
('tenderness','Tenderness','tender quiet affection',1.0,true),
('contentment','Contentment','contented quiet happiness',1.0,true),
('calm_focus','Calm Focus','calm focused presence',1.0,true)
ON CONFLICT (slug) DO NOTHING;