UPDATE blog_posts SET is_noindexed = true, updated_at = now()
WHERE slug IN (
  'best-enrichment-toys-cats', 'best-pet-toys-guide-dogs-cats-entertainment', 'best-toys-for-bored-cats',
  'cat-enrichment-toys', 'cat-enrichment-toys-mental-stimulation-guide', 'cat-puzzle-toys',
  'cat-toys-playtime-interactive-guide-2026', 'interactive-cat-entertainment-sets-mental-stimulation-guide',
  'interactive-cat-toys-guide', 'interactive-play-benefits',
  'indoor-cat-enrichment-how-to-keep-your-cat-happy-indoors', 'indoor-cat-enrichment-mental-stimulation',
  'indoor-cat-entertainment', 'indoor-cat-entertainment-rainy-days', 'indoor-cat-environment-guide',
  'how-to-entertain-indoor-cats',
  'cat-scratching-post-health-behavior-protection', 'cat-scratching-posts-trees-complete-guide-2026',
  'cat-scratching-posts-trees-furniture-guide-2026', 'cat-scratching-solutions',
  'cat-climbing-furniture', 'cat-tree-buying-guide-perfect-tower-feline',
  'cat-tree-house-buying-guide-what-to-look-for', 'choosing-safe-cat-tree-indoor-cats',
  'flower-cat-tower-trendy-climbing-trees', 'flower-cat-tree-instagram-worthy-furniture-2026',
  'cat-condo-vs-cat-tower-whats-the-difference',
  'cat-litter-box-training-guide', 'premium-cat-litter-guide',
  'self-cleaning-litter-box-reviews-guide', 'self-cleaning-litter-boxes-automatic-cat-solutions-2026',
  'ultimate-guide-automatic-cat-litter-boxes-smart-pet-owners',
  'covered-litter-boxes-odor-control-guide-2026',
  'cat-grooming-habits', 'essential-cat-grooming-tips-healthy-beautiful',
  'cat-communication-guide', 'decoding-cat-meows-communication',
  'understanding-cat-sleeping-habits',
  'cat-water-fountains', 'cat-stainless-steel-water-fountain-health-benefits',
  'cat-food-nutrition-guide-best-diet-2026', 'cat-nutrition-guide-best-food-feline',
  'senior-cat-care-aging-feline-health', 'senior-cat-comfort',
  'catios-indoor-cat-safe-outdoor-access-guide', 'creating-safe-outdoor-space-cat',
  'how-to-choose-a-cat-carrier-for-travel', 'ultimate-guide-pet-carrier-backpacks-travel-cat-dog',
  'cat-friendly-garden-guide', 'cat-grass-benefits', 'cat-proof-christmas-tree-guide',
  'cat-purring-science-guide', 'cat-exercise-wheels-indoor-cat-fitness-revolution',
  'diy-cat-tree-real-tree-ideas', 'pet-safe-plants-cat-trees',
  'litter-box-furniture-transforming-cat-ownership', 'freeze-dried-cat-treats',
  'leaving-cats-home-alone-how-long-safe', 'pregnant-cat-care',
  'feline-hyperthyroidism-guide', 'feline-kidney-disease-guide',
  'heated-pet-beds-winter-comfort-guide-cats-dogs-2026',
  'pet-body-language-understanding-dogs-cats-communication',
  'pet-grooming-guide-dogs-cats-home', 'pet-nutrition-guide-feeding-dogs-cats',
  'pet-supplements-vitamins-nutritional-health-guide-2026',
  'senior-pet-care-aging-dogs-cats-guide', 'dogs-cats-living-together',
  'multi-species-household-harmony', 'importance-dental-care-dogs-cats',
  'microchipping-pets', 'safe-houseplants-homes-curious-cats',
  'cat-tree-placement-guide-best-location', 'giant-cat-tree-towers-ultimate-vertical-playground-feline',
  'kitty-condo-vs-cat-tree-comparison-guide', 'cat-self-grooming-brushes',
  'cat-steam-brush-grooming-revolution-guide', 'cat-scratching-post-guide-large-cats'
)
AND (is_noindexed = false OR is_noindexed IS NULL)