
CREATE TABLE IF NOT EXISTS public.pinterest_category_creative_pools (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL,
  pool_type text NOT NULL CHECK (pool_type IN ('headline','hook','cta','angle','benefit')),
  value text NOT NULL,
  weight integer NOT NULL DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  times_used integer NOT NULL DEFAULT 0,
  last_used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (category, pool_type, value)
);

GRANT SELECT ON public.pinterest_category_creative_pools TO authenticated;
GRANT ALL ON public.pinterest_category_creative_pools TO service_role;

ALTER TABLE public.pinterest_category_creative_pools ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage category creative pools"
ON public.pinterest_category_creative_pools
FOR ALL TO authenticated
USING (public.has_role(auth.uid(), 'admin'))
WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Service role full access category pools"
ON public.pinterest_category_creative_pools
FOR ALL TO service_role
USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_cat_pools_cat_type_active
  ON public.pinterest_category_creative_pools (category, pool_type, is_active);

INSERT INTO public.pinterest_category_creative_pools (category, pool_type, value) VALUES
('cat_trees','headline','Built for Real Climbers'),
('cat_trees','headline','The Last Tree You''ll Buy'),
('cat_trees','headline','Sturdy Enough for Two'),
('cat_trees','headline','Furniture-Grade Cat Tower'),
('cat_trees','headline','Quiet Floors, Happy Cat'),
('cat_trees','headline','Made for Tall Ceilings'),
('cat_trees','headline','No Wobble, No Tip-Over'),
('cat_trees','headline','Cat Tree That Fits Your Home'),
('cat_trees','hook','Watched her climb it twice before unboxing finished'),
('cat_trees','hook','Replaced three flimsy towers with this one'),
('cat_trees','hook','He naps on the top perch every afternoon now'),
('cat_trees','hook','Solid wood, not the usual cardboard core'),
('cat_trees','cta','See the build'),
('cat_trees','cta','Compare heights'),
('cat_trees','cta','Shop the tower'),
('cat_trees','angle','Status / Premium build'),
('cat_trees','angle','Multi-cat household'),
('cat_trees','angle','Small space friendly'),
('cat_trees','benefit','Solid hardwood frame'),
('cat_trees','benefit','Holds 30+ lbs per perch'),
('cat_trees','benefit','Replaceable sisal posts'),
('dog_beds','headline','Orthopedic Relief, Real Sleep'),
('dog_beds','headline','The Bed Senior Dogs Pick'),
('dog_beds','headline','Washable Cover, Cooling Core'),
('dog_beds','headline','For Dogs With Stiff Joints'),
('dog_beds','headline','Calm Sleep, Less Pacing'),
('dog_beds','headline','A Bed That Holds Its Shape'),
('dog_beds','headline','Quiet Nights for Anxious Dogs'),
('dog_beds','hook','He stopped circling and just slept'),
('dog_beds','hook','Vet recommended for her hip dysplasia'),
('dog_beds','hook','Six months in, still no flat spots'),
('dog_beds','cta','See the bed'),
('dog_beds','cta','Pick a size'),
('dog_beds','cta','Shop orthopedic beds'),
('dog_beds','angle','Senior comfort'),
('dog_beds','angle','Anxiety relief'),
('dog_beds','angle','Durability proof'),
('dog_beds','benefit','Memory foam base'),
('dog_beds','benefit','Machine-washable cover'),
('dog_beds','benefit','Non-skid bottom'),
('carriers','headline','Airline-Approved & Cozy'),
('carriers','headline','Travel Without the Stress'),
('carriers','headline','Built for Anxious Pets'),
('carriers','headline','Fits Under Every Seat'),
('carriers','headline','Vet Visits, Made Quiet'),
('carriers','headline','A Carrier They Walk Into'),
('carriers','headline','Padded Sides, Real Ventilation'),
('carriers','hook','She walks in by herself now'),
('carriers','hook','First flight, zero whining'),
('carriers','hook','Folded flat in the overhead bin'),
('carriers','cta','See the carrier'),
('carriers','cta','Check airline fit'),
('carriers','cta','Shop travel gear'),
('carriers','angle','Travel ease'),
('carriers','angle','Anxiety reduction'),
('carriers','angle','Airline compliance'),
('carriers','benefit','TSA-friendly dimensions'),
('carriers','benefit','Mesh on all four sides'),
('carriers','benefit','Removable washable pad'),
('cat_essentials','headline','The Daily Setup Cats Need'),
('cat_essentials','headline','Smarter Bowls, Calmer Mealtimes'),
('cat_essentials','headline','Whisker-Friendly From Day One'),
('cat_essentials','headline','Built for the Way Cats Drink'),
('cat_essentials','headline','Less Mess, More Routine'),
('cat_essentials','headline','Tiny Upgrades, Big Difference'),
('cat_essentials','hook','She finally drinks from her bowl'),
('cat_essentials','hook','No more whisker fatigue at dinner'),
('cat_essentials','hook','One small swap, calmer mornings'),
('cat_essentials','cta','See the set'),
('cat_essentials','cta','Shop essentials'),
('cat_essentials','cta','Build the routine'),
('cat_essentials','angle','Daily routine'),
('cat_essentials','angle','Whisker comfort'),
('cat_essentials','angle','Hydration health'),
('cat_essentials','benefit','Wide shallow bowl'),
('cat_essentials','benefit','Food-grade ceramic'),
('cat_essentials','benefit','Non-slip silicone base'),
('toys','headline','The Toy They Actually Play With'),
('toys','headline','Built to Outlast Aggressive Chewers'),
('toys','headline','Indoor Cats, Real Exercise'),
('toys','headline','Engages Even Bored Dogs'),
('toys','headline','Quiet Play for Apartments'),
('toys','headline','The Toy in Every Rotation'),
('toys','hook','He brings it to me every morning'),
('toys','hook','Two months in, still intact'),
('toys','hook','Finally a puzzle that tires her out'),
('toys','cta','See it in action'),
('toys','cta','Shop the toy'),
('toys','cta','Pick a level'),
('toys','angle','Enrichment & exercise'),
('toys','angle','Indestructibility'),
('toys','angle','Indoor energy burn'),
('toys','benefit','Non-toxic natural rubber'),
('toys','benefit','Treat-dispensing puzzle'),
('toys','benefit','Floats and bounces unpredictably'),
('litter','headline','Cleaner Litter, Quieter Mornings'),
('litter','headline','A Box That Manages Itself'),
('litter','headline','Less Tracking, Less Dust'),
('litter','headline','Made for Multi-Cat Homes'),
('litter','headline','Odor Control That Actually Works'),
('litter','headline','The Box Cats Don''t Avoid'),
('litter','hook','Three cats, one box, zero smell'),
('litter','hook','First week and I forgot it was there'),
('litter','hook','No more tracked litter on the rug'),
('litter','cta','See the box'),
('litter','cta','Shop the system'),
('litter','cta','Compare models'),
('litter','angle','Odor control'),
('litter','angle','Multi-cat capacity'),
('litter','angle','Low maintenance'),
('litter','benefit','Sealed odor chamber'),
('litter','benefit','Auto-cycle after each use'),
('litter','benefit','Low-track granule design')
ON CONFLICT (category, pool_type, value) DO NOTHING;
